### ISSUE TITLE
[FEATURE REQ] Update to use MySQL flexible server in passwordless docs

### ISSUE THREAD

**Issue by saragluna** [microsoft/spring-cloud-azure#1001]
**Is your feature request related to a problem? Please describe.**
MySQL flexible server has been GAed. https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-azure-ad-authentication. We should update all our usage of MySQL in passwordless docs from single server to flexible server.

**Describe the solution you'd like**
- Update the quickstart docs
  - [JAVA](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/connect-java)
  - [JDBC](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless)
  - [JPA](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-mysql?tabs=passwordless)
- Update the [migration doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-mysql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cjava%2Capp-service%2Capp-service-identity)
- Update the [tutorial doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?tabs=mysql)
- Update the [reference doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#mysql-support)
- Update the README files in sdk/jdbc/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by Netyyyy** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/214005

**Comment by Netyyyy** [comment]
close for the above PRs merged
