### ISSUE TITLE
[FEATURE REQ] Show multiple version for reference doc in MS doc

### ISSUE THREAD

**Issue by moarychan** [microsoft/spring-cloud-azure#1013]
**Is your feature request related to a problem? Please describe.**

Since the multiple major versions reference doc of Spring Cloud Azure has been published on the GitHub IO site, but the MS doc website can only display one version 4.x reference doc of Spring Cloud Azure, we would like to keep two or more major versions(4.x and 6.x) in the MS reference doc of Spring Cloud Azure.

**Describe the solution you'd like**

The customers can select a special reference doc version of Spring Cloud Azure on MS doc. Customers should have the same experience on this website [Rerenence doc of Spring Security](https://docs.spring.io/spring-security/reference/index.html), they can change the reference doc version of the Spring Cloud Azure, and do not need to change the whole URL for a special version.

Sach as below:
![image](https://user-images.githubusercontent.com/19926623/203882380-6122421e-9ead-4b5c-ae33-0161c54bac41.png)

**Describe alternatives you've considered**
N/A

**Additional context**

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by stliu** [comment]
is this resolved or not?

And, you should make the issue more specific to the problem you're trying to resolve.

I don't think you're trying to add show multi version feature to ms doc, that's can't be your goal, unless you work for ms doc team and me in the same time

**Comment by moarychan** [comment]
Not resolved.

Currently, our needs have been informed to the doc team, and we and the doc team have already agreed to implement [a transition plan to support viewing the reference documentation for both major versions(4.x and 6.x)](https://github.com/Azure/azure-sdk-for-java/issues/31896), this achievement will not be the final goal for this issue, we should keep pushing the MS doc team to deliver this feature.

**Comment by stliu** [comment]
@chenrujun  I'm assigning this to you, please consider this requirement when designing our ms doc toc

**Comment by chenrujun** [comment]
@stliu 

> @chenrujun I'm assigning this to you, please consider this requirement when designing our ms doc toc

OK, will do.

**Comment by chenrujun** [comment]
@stliu 

> keep it simple first, the goal is to explain how to use our product for spring boot 3 / spring cloud azure 6 customers.
> 
> I can think two options here:
> 
> 1. we don't have two version of doc, but one doc only, if any chapter in the doc has difference between 4.x and 6.x, we doc that in the doc explicitly, I don't think there are too many places of differences
> 2. we just use different level of toc for that, one for 4.x and one for 6.x

I agree with you.

@moarychan told me that except `migration guide` and `what's new`, there is no difference between 4.x and 6.x.

If you agree, I'll move the 2 files from this PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3847 to current MS doc, then close this PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3847

**Comment by moarychan** [comment]
@chenrujun  please note the [PR description](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3847#issue-1451061927) about other deleted files.

I understand this is still a transition plan for us.
The new solution should be simple and clear for the two major versions, but from a long time perspective, assume the SCA has already released versions 4.10.0 and 6.6.0, the customer will be confused about how to see the reference doc for the previous version, such as 4.5.0 and 6.5.0, no entry for them to view the reference doc versioned by SCA, we will couple multiple versions together, and it will become bloated.

**Comment by chenrujun** [comment]
Here is current plan:

Use this method to display document for multiple versions:

> This article applies to Version 4.x Version 5.x

![image](https://user-images.githubusercontent.com/13167207/212855620-c6db0867-4692-4b8a-950c-c4470a274025.png)

Refs: https://learn.microsoft.com/en-us/azure/spring-apps/tutorial-alerts-action-groups

**Comment by fangjian0423** [comment]
@hui1110 could you pls help to do this? thanks.

**Comment by hui1110** [comment]
The [changes ](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4068/files#diff-927e14914e197b066cbfe3863b006601a2416530658a9730f936db2a8f37e6faR13)have been merged, close it now.
