### ISSUE TITLE
Use PostgreSQL Flexible server in docs

### ISSUE THREAD

**Issue by Netyyyy** [microsoft/spring-cloud-azure#1023]
**Is your feature request related to a problem? Please describe.**
PostgreSQL flexible server has been GAed. https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication. We should update all our usage of PostgreSQL in passwordless docs from single server to flexible server.

**Describe the solution you'd like**
- Update the quickstart docs
  - [JAVA](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java)
  - [JDBC](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless)
  - [JPA](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql?tabs=passwordless)
- Update the [migration doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cjava%2Cservice-connector%2Cservice-connector-identity%2Cassign-role-service-connector)
- Update the [tutorial doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?tabs=mysql)
- Update the [reference doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#postgresql-support)
- Update the README files in sdk/jdbc/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by hui1110** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/217351

**Comment by hui1110** [comment]
The command to set up `Azure AD Admins` for `PostgreSQL Flexible Server` using `Azure CLI` will be released next month and will continue to update the documentation after the command is released.

**Comment by fangjian0423** [comment]
@hui1110 

QuickStart for PostgreSQL passwordless need to be written in [Quickstart: Use Java and JDBC with Azure Database for PostgreSQL Flexible Server](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/connect-java), we can refer this [link](https://learn.microsoft.com/en-us/azure/postgresql/single-server/connect-java?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json&tabs=passwordless).

[QuickStart for MySQL passwordless](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/connect-java?tabs=passwordless) has been written before.

**Comment by fangjian0423** [comment]
Differences between single server and flexible server, we need mention them in flexible docs.

1. postgresql single server has only one Azure AD administrator but pg flexible server may have more than 1

2. Manage Azure AD roles using SQL is different

flexible server: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users
single server: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless#create-a-postgresql-non-admin-user-and-grant-permission

**Comment by backwind1233** [comment]
> The command to set up `Azure AD Admins` for `PostgreSQL Flexible Server` using `Azure CLI` will be released next month and will continue to update the documentation after the command is released.
> 
> ```
> az postgres server ad-admin create \
>     --resource-group $AZ_RESOURCE_GROUP \
>     --server-name $AZ_DATABASE_SERVER_NAME \
>     --display-name $CURRENT_USERNAME \
>     --object-id $CURRENT_USER_OBJECTID
> ```
> 
> -->
> 
> ```
> az postgres flexbile-server ad-admin create \
>     --resource-group $AZ_RESOURCE_GROUP \
>     --server-name $AZ_DATABASE_SERVER_NAME \
>     --display-name $CURRENT_USERNAME \
>     --object-id $CURRENT_USER_OBJECTID
> ```

we can check the release [note](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli)

**Comment by fangjian0423** [comment]
> Created PR:[MicrosoftDocs/azure-dev-docs-pr#3910](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3910)

This PR don't update [JDBC quickstart](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless) and [JPA quickstart](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql?tabs=passwordless) docs.

**Comment by hui1110** [comment]
PR merged, now close this issue.
