### ISSUE TITLE
[FEATURE REQ] Remove the Key Vault SDK content from the Azure Spring Apps KV doc

### ISSUE THREAD

**Issue by saragluna** [microsoft/spring-cloud-azure#1024]
**Is your feature request related to a problem? Please describe.**
We should improve this doc by removing the KV secrets SDK part, https://learn.microsoft.com/en-us/azure/spring-apps/tutorial-managed-identities-key-vault?source=recommendations&tabs=system-assigned-managed-identity. 

For an Azure Spring Apps application that wants to integrate with Azure Key Vault Secrets, the better choice should always be using the Spring Cloud Azure Key Vault starter, either for secret management or for auto-wiring secret clients.

The SDK part in this doc is very confusing to users.

**Describe the solution you'd like**
Remove the SDK part from this doc.

**Describe alternatives you've considered**
N/A

**Additional context**
> @chenrujun:
And even if the doc want to demonstrate the usage of kv secret client, it should use the auto-configured one.

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by fangjian0423** [comment]
Close it via https://github.com/MicrosoftDocs/azure-docs-pr/pull/215032.
