### ISSUE TITLE
[FEATURE REQ]Add tips that 4.x version of Spring Cloud Azure certificates doesn't support TLS/mTLS

### ISSUE THREAD

**Issue by fangjian0423** [microsoft/spring-cloud-azure#1031]
**Is your feature request related to a problem? Please describe.**

We should add tips to explain 4.x version of Spring Cloud Azure certificates starter doesn't support TLS/mTLS, it only does the auto-configuration of Key Vault certificate clients, https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.

**Describe the solution you'd like**

Add tips at the top of article.

**Describe alternatives you've considered**

N/A

**Additional context**

https://github.com/MicrosoftDocs/azure-dev-docs/issues/853

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by hui1110** [comment]
PR to fix the issue: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3791

**Comment by hui1110** [comment]
PR merged, now close this issue.
