### ISSUE TITLE
[FEATURE REQ] Allow users to define the claimToAuthorityPrefix when application_type is web_application or web_application_and_resource_server

### ISSUE THREAD

**Issue by fxpaquette** [microsoft/spring-cloud-azure#1052]
**Is your feature request related to a problem? Please describe.**
When application_type is resource_server, users can define a custom claimToAuthorityPrefix (defaults to "APPROLE_") with the property `spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map.roles`. However, for web_application the prefix is hardcoded inside the **AadOAuth2UserService.extractRolesFromIdToken** method.

**AadOAuth2UserService.java**
```
Set<String> extractRolesFromIdToken(OidcIdToken idToken) {
        return Optional.ofNullable(idToken)
                       .map(token -> (Collection<?>) token.getClaim(ROLES))
                       .filter(obj -> obj instanceof List<?>)
                       .map(Collection::stream)
                       .orElseGet(Stream::empty)
                       .filter(s -> StringUtils.hasText(s.toString()))
                       .map(role -> AuthorityPrefix.APP_ROLE + role)
                       .collect(Collectors.toSet());
    }
```

**Describe the solution you'd like**
Let users define the claimToAuthorityPrefix when application_type is web_application or web_application_and_resource_server by adding a similar property as `spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map.roles` and using this property in the above method.

**Describe alternatives you've considered**
For now, I think the alternative is to create an `OAuth2UserService` bean by extending the `AadOAuth2UserService` class and overriding the `extractRolesFromIdToken` method.

**Additional context**
I am using spring-cloud-azure-starter-active-directory 6.0.0-beta.3

**Information Checklist**
- [ x] Description Added
- [x ] Expected solution specified

**Comment by hui1110** [comment]
Hi, @fxpaquette   thanks for reaching out, our repo has to be migrated to [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring), so I copied the current issue to that repo, let's use that [issue ](https://github.com/Azure/azure-sdk-for-java/issues/33560)to track.

**Comment by hui1110** [comment]
Closing this, redirect to https://github.com/Azure/azure-sdk-for-java/issues/33560.
