### ISSUE TITLE
[QUERY] How to configure multiple blob storage containers in yml file (Spring boot)

### ISSUE THREAD

**Issue by otaku0304** [microsoft/spring-cloud-azure#1059]
**Query/Question**

How to configure multiple blob storage containers in yml file (Spring boot)

***Why is this not a Bug or a feature Request?***

Because it is working for a single container name and it is not working for multiple containers, also it may be the reason that I was not configuring the container-name properly.

**Content (please complete the following information if possible):**

Below is the format of the code that is how I mentioned in my yml file. And you can also see only one container name is mentioned it's working well, but if I use two names no one is working, developer is one of the container name and fullstack is the second container name.

With the single container-name only one container is working.
blob:
  connection-string: ${blob-connection-string}
  container-name:  developer

With the multiple container-name no container is working.
blob:
  connection-string: ${blob-connection-string}
  container-name:  developer, fullStack

**Comment by Netyyyy** [comment]
Hi @otaku0304 , [this](https://github.com/microsoft/spring-cloud-azure/discussions/972) may be helpful for you

**Comment by saragluna** [comment]
@otaku0304 which API you are using? The Spring Resource or the Storage Container? If it's storage container, the autoconfiguration doesn't support configuring multiple beans automatically, but you can autowire the builder (if with the same connection string), and create new container instance by yourself.

**Comment by otaku0304** [comment]
Actually its works.

> @otaku0304 which API you are using? The Spring Resource or the Storage Container? If it's storage container, the autoconfiguration doesn't support configuring multiple beans automatically, but you can autowire the builder (if with the same connection string), and create new container instance by yourself.

**Comment by otaku0304** [comment]
> Hi @otaku0304 , [this](https://github.com/microsoft/spring-cloud-azure/discussions/972) may be helpful for you

@Netyyyy thanks for your help.

**Comment by saragluna** [comment]
Closing this issue now.
