### ISSUE TITLE
The version 5.11.0 of the starter is not compatible with the latest version of msal4j 1.15.0

### ISSUE THREAD

**Issue by rawadolb** [microsoft/spring-cloud-azure#1062]
**If i force the latest version of msal4j 1.15.0 in my project with spring-cloud-azure-starter-keyvault 5.11.0 have this error : **

> An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.azure.identity.implementation.IdentityClientBase.getManagedIdentityConfidentialClient(IdentityClientBase.java:393)

The following method did not exist:

    'com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.logPii(boolean)'

The calling method's class, com.azure.identity.implementation.IdentityClientBase, was loaded from the following location:

    jar:file:/C:/Users/xxxxx/.m2/repository/com/azure/azure-identity/1.11.4/azure-identity-1.11.4.jar!/com/azure/identity/implementation/IdentityClientBase.class

The called method's class, com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder, is available from the following locations:

    jar:file:/C:/Users/xxxxx/.m2/repository/com/microsoft/azure/msal4j/1.15.0/msal4j-1.15.0.jar!/com/microsoft/aad/msal4j/ConfidentialClientApplication$Builder.class

The called method's class hierarchy was loaded from the following locations:

    com.microsoft.aad.msal4j.ConfidentialClientApplication.Builder: file:/C:/Users/xxxxx/.m2/repository/com/microsoft/azure/msal4j/1.15.0/msal4j-1.15.0.jar
    com.microsoft.aad.msal4j.AbstractClientApplicationBase.Builder: file:/C:/Users/xxxxxxxx/.m2/repository/com/microsoft/azure/msal4j/1.15.0/msal4j-1.15.0.jar
    com.microsoft.aad.msal4j.AbstractApplicationBase.Builder: file:/C:/Users/xxxxxxxxx/.m2/repository/com/microsoft/azure/msal4j/1.15.0/msal4j-1.15.0.jar -->

**To Reproduce**

Workaround :
use the latest version of azure-identity

> <dependency>
     <groupId>com.azure</groupId>
     <artifactId>azure-identity</artifactId>
     <version>1.12.0</version>
  </dependency>

I believe you need to integrate these versions in your future release : 

><dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
    <version>5.12.0-beta.1</version>
</dependency>

**Comment by Netyyyy** [comment]
Hi @rawadolb , thanks for reaching out.
Spring Cloud Azure 5.12 has fixed it.

**Comment by Netyyyy** [comment]
close for fixed
