### ISSUE TITLE
Multiple app registration in one spring boot application

### ISSUE THREAD

**Issue by gurkancakir** [microsoft/spring-cloud-azure#1064]
**Question**
We would like to use two app registrations, one on Azure China and the other on Azure Global, within an application. While connecting to the service buses on Azure Global with one, we would like to access the service buses on Azure Global with the other.

Only one app registration information is specified in the config. Do we have a chance to realize the above situation in a single spring boot application?

**Comment by Netyyyy** [comment]
close for moved to current repo
