### ISSUE TITLE
redis cache creation success but resource in portal is not available

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/spring-cloud-azure#117]
## Expected Behavior
* After autoconfiguration prompt redis Cache created, the resource in portal should be available.

## Current Behavior
* The availability between SDK and portal is inconsistent.

## Possible Solution
* SDK update.

## Your Environment
* Version used:
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by yaweiw** [comment]
@Incarnation-p-lee @warrenzhu25 @sophiaso see my comments in #236 . shall we ask users to bring their own resources rather using auto provisioning?

**Comment by Incarnation-p-lee** [comment]
Yes, make sense, I think we'd better suggest use to create their own redis instead of auto provision, as it cost too long there.
