### ISSUE TITLE
Azure Storage Emulator

### ISSUE THREAD

**Issue by shizhMSFT** [Microsoft/spring-cloud-azure#131]
Does `spring-cloud-azure-storage` support [Azure Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator)?

**Comment by warrenzhu25** [comment]
I haven't seen any relationship between both. Could you specify?

**Comment by shizhMSFT** [comment]
Azure Storage Emulator is used to develop apps leveraging the Azure Storage locally without an Azure subscription or incurring any costs. Similarly, as a developer, how do I create/test an app based on spring-cloud-azure-storage locally without a subscription? I don't want to pay before my app is in production.

**Comment by shizhMSFT** [comment]
This issue is out of the scope of this project.
