### ISSUE TITLE
[question] what's difference between spring-cloud-azure-xxx-starters and spring-azure-xxx-starters

### ISSUE THREAD

**Issue by yungezz** [Microsoft/spring-cloud-azure#133]
The samples works well!

While as a user, I'm confusing on what's difference between spring-cloud-azure-xxx-starters and spring-azure-xxx-starters. Repos layout is same, naming is similar, autoconfig is similiar, even part of functionality showed in sample. User has no idea on choosing which one. It's will be very useful in spring cloud repo readme to  call out what's main differentiator and characteristic of spring cloud azure.

btw, i remembered original design of spring cloud is to incorporate all spring cloud azure packages in one scenario to complete an end to end story. Is it still true? It will be great if some link or story telling to let people know when and how to use spring-cloud-azure.

**Comment by warrenzhu25** [comment]
`spring-cloud-azure-xxx-starters` take advantage of credential file and Azure management SDK to fetch and auto config related properties without user fill these by themselves.
`spring-azure-xxx-starters` just auto config related service SDK by needing user to fill all properties by themselves

**Comment by yungezz** [comment]
so the difference between spring-cloud-xxx-starter and spring-xxx-starter is only configuration? What I mean is that need more info on differentiator aspects of spring-cloud-xxx-starter, comparing of spring-xxx-starter. not auto-configure config item itself.
