### ISSUE TITLE
need way to disable telemetry

### ISSUE THREAD

**Issue by yungezz** [Microsoft/spring-cloud-azure#134]
saw some telemetry collecting trace in log, want to disable it, but didn't find way to do it.

**Comment by Incarnation-p-lee** [comment]
For now cannot disable AI log, because it use `System.err.println` for print logs.

**Comment by Incarnation-p-lee** [comment]
Will update the configuration in sample code.

**Comment by Incarnation-p-lee** [comment]
add 
`spring.cloud.azure.telemetry.enable=true` to application.properties.
for README for each sample.
