### ISSUE TITLE
[eventhub-kafka-sample] Event hub creation should be before property modification

### ISSUE THREAD

**Issue by miaosakurai** [Microsoft/spring-cloud-azure#141]
In the doc, step 3 and step 4 is:
3. Update application.properties file
4. Create Kafka enabled event hub. Please follow How to create Kafka enabled Event Hubs

If kafka enabled event hubs has to be created manually, the step 4 should be done before step 3, because users should have a existing Kafka enabled event hub before they fill the eventhub namespace in application.properties.

**Comment by warrenzhu25** [comment]
Good point. Will update the doc.
