### ISSUE TITLE
Configuration options are not fully specified in the table of user guidance 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/spring-cloud-azure#232]
The following configuration options are not specified in the table of 
https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-eventhub-stream-binder

spring.cloud.stream.bindings.input.destination=[eventhub-name]
spring.cloud.stream.bindings.input.group=[consumer-group]
spring.cloud.stream.bindings.output.destination=[eventhub-name]

**Comment by warrenzhu25** [comment]
These properties are standard Spring Cloud stream properties. Users might want to check official doc
