### ISSUE TITLE
Support message consume operation retry in binder

### ISSUE THREAD

**Issue by warrenzhu25** [microsoft/spring-cloud-azure#275]
This is controlled by `spring.cloud.stream.bindings.input.consumer.max-attempts=1`. And the implementation should be rely on spring `RetryTemplate`.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
