### ISSUE TITLE
Support produce message failure auto retry

### ISSUE THREAD

**Issue by warrenzhu25** [microsoft/spring-cloud-azure#310]
In message related module, we should auto retry when producing messages failed. The following parts should be considered:

1. How to determine whether a produce is retriable or not. Simply retrying might result in duplicate messages.
2. Let you specify max retry times and retry backoff policy.
3. How to react when exceed max retry times. Throw exception, log or send to another error channel.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
