### ISSUE TITLE
Update `spring-starter-*` packages to a better name

### ISSUE THREAD

**Issue by xscript** [microsoft/spring-cloud-azure#314]
Now we have two packages with name prefix `spring-starter`. This doesn't align with neither `spring-boot-starter-` nor `spring-cloud-starter-`, and is very confusing to developers.
We should find better names for them.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
