### ISSUE TITLE
CheckpointConfig.java is missing from 1.0.0.M2 version

### ISSUE THREAD

**Issue by ranjan545486** [Microsoft/spring-cloud-azure#325]
https://mvnrepository.com/artifact/com.microsoft.azure/spring-integration-azure/1.0.0.M2 is having a class missing (CheckpointConfig.java).

This class is present in the master branch. https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-integration-azure/spring-integration-azure-core/src/main/java/com/microsoft/azure/spring/integration/core/api/CheckpointConfig.java 

Can there be an updated release with this class present?

**Comment by warrenzhu25** [comment]
Thanks for bringing this out. We just made some changes in master branch, but the homepage sample has been updated. It should be pointing to sample of the latest release 1.0.0.M2. 

You can follow the samples for 1.0.0.M2 in https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-samples.

**Comment by warrenzhu25** [comment]
Close this.
