### ISSUE TITLE
spring cloud connector for Kubernetes OSB ( Azure ) 

### ISSUE THREAD

**Issue by cforce** [microsoft/spring-cloud-azure#397]
The project https://github.com/spring-cloud/spring-cloud-connectors provides easy auto configuration/binding of managed services using service broker concepts and enviroments managment for CF and Heroku.

Please add support for such automatic lookup in spring cloud apps with OSB bindings for Azure managed services (https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-aks.md#configure-the-cluster-with-open-service-broker-for-azure , https://github.com/Azure/open-service-broker-azure#getting-started-on-kubernetes ) e.g. using Kubernetes ns/ environment / tags for a broad developer experience.
With managed bindings make us of rotating credentials to improve security.
Maybe it oversaw something as there are many projects split up between pivotal and microsoft and we have to platforms (cloudfoundry,kubernetes) to be supported. 

Related:
https://github.com/Microsoft/azure-spring-boot/issues/262 
https://github.com/spring-cloud/spring-cloud-connectors/issues/250
https://github.com/spring-cloud/spring-cloud-connectors/issues/248

**Comment by warrenzhu25** [comment]
If you mean supporting open service broker on cloud foundry such as #344, we will support such feature soon. If you mean other things, could you clarify?

**Comment by cforce** [comment]
I mean to support OSB for Azure on Azure Kubernetes Services by implementing a new "Spring Cloud Connector" for  his based on the concepts and interfaces of  https://cloud.spring.io/spring-cloud-connectors/ .
The connector has to work with OSB on Kubernetes (without/independent of Cloudfoundry).

**Comment by warrenzhu25** [comment]
We have no plan to support this. Welcome contribution.

**Comment by scottfrederick** [comment]
The Spring Cloud Connectors project is [in maintenance mode](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services), in favor of the newer [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project. I would not recommend implementing a Connectors extension for the Azure service broker.

**Comment by saragluna** [comment]
Closing this now.
