### ISSUE TITLE
Config - Create or delete watch key does not trigger a config refresh

### ISSUE THREAD

**Issue by sophiaso** [microsoft/spring-cloud-azure#488]
Reproduce step:
1. Enable config watch feature
2. Configure watch key (do not create the watch key in config store)
3. Start the application 
4. Create the watch key in the config store
5. Config properties will not refresh
6. Change the watch key again, properties will refresh
7. Delete the watch key, the config properties will not refresh

It's a minor issue, but user may expect at least refresh at step 5?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
