### ISSUE TITLE
EventHubMessageConverter ignores headers

### ISSUE THREAD

**Issue by andreasreinhardt** [Microsoft/spring-cloud-azure#489]
## Expected Behavior
* headers set in a Spring message are not set in EventData Azure message
* headers set from EventHub messages are net set in Spring messages

## Current Behavior
* headers are ignored

## Possible Solution
* override `setCustomHeaders` and `buildCustomHeaders` in `EventHubMessageConverter` 

## Steps to Reproduce (for bugs)
* use the eventhubs-binder-sample and extend the SourceExample to add a custom header with some value
* extend SinkExample to receive this custom header
* the value of this header is null

## Branch
* master

## Your Environment
* Version used: 1.1.0.M1
* Operating System and version (desktop or mobile): Linux

**Comment by warrenzhu25** [comment]
Thanks for reporting this issue. We could put custom header from spring message into `EventData#getProperties()` and vice versa. It would be great you can send a pull request to fix this.

**Comment by andreasreinhardt** [comment]
The linked implementation worked for me. Feel free to modify

**Comment by andreasreinhardt** [comment]
Do you mind to create a release with this fix and push it on Maven Central? This would help me very much to use it.

**Comment by warrenzhu25** [comment]
Will release next week.

**Comment by sophiaso** [comment]
@andreasreinhardt We have a snapshot version released, you may also try with a snapshot version first. 
```
<repositories>
	<repository>
		<id>nexus-snapshots</id>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```

**Comment by andreasreinhardt** [comment]
Thank you very much!
