### ISSUE TITLE
Documentation links 404

### ISSUE THREAD

**Issue by jemag** [Microsoft/spring-cloud-azure#502]
Multiple links in the documentation return 404. For example, some on https://github.com/Microsoft/spring-cloud-azure and also https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder

**Comment by warrenzhu25** [comment]
I have fixed homepage link. If you see other broken links, could you help send PR? Thanks a lot.
