### ISSUE TITLE
"spring-cloud-azure-starters" artifact missing issue

### ISSUE THREAD

**Issue by rgampa** [Microsoft/spring-cloud-azure#506]
I am trying to use below dependency in my project

```
           <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>spring-cloud-starter-azure-appconfiguration-config</artifactId>
                <version>1.1.0.M1</version>
            </dependency>
```

Which has parent pom dependency with `spring-cloud-azure-starters` pom version `1.1.0.M1`. But in maven central repository that version is not available https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:spring-cloud-azure-starters&core=gav. 

Tried with version `1.1.0.M2` too. The latest version for `spring-cloud-azure-starters` is `1.1.0.RC5`, but couldn't find child module `spring-cloud-starter-azure-appconfiguration-config` with the same version. Can you please look into this issue and make sure the documentation https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app is latest.

**Comment by sophiaso** [comment]
Hi @rgampa, thanks for trying the config starter and report issue. The milestone version for configuration modules are different with RC modules, no `RC` versions for configuration modules have been released yet. But indeed, there is some dependency problem for the previous release. Will release a new milestone version(i.e., `1.1.0.M3`) ASAP. The [doc](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app) content is correct, besides the version.

If you want to try the configuration feature before the new milestone version released, you can try the [snapshot](https://github.com/Microsoft/spring-cloud-azure#snapshots) version first. 

Will update here again once the new milestone version is released.

**Comment by rgampa** [comment]
Thanks @sophiaso.

**Comment by sophiaso** [comment]
@rgampa A new `1.1.0.M3` has been released, [link](https://search.maven.org/search?q=a:spring-cloud-starter-azure-appconfiguration-config).

**Comment by sophiaso** [comment]
@rgampa Close this issue now, feel free to reopen if you still have problem.

**Comment by antonior0409** [comment]
Hi all
I'm trying to integrate
`           <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>spring-cloud-starter-azure-appconfiguration-config</artifactId>
                <version>1.1.0.M3</version>
            </dependency>
`
But build file due to Milestone version usage, how can I deal with such issue?
when a release version will be available?

Thanks in advance

**Comment by sophiaso** [comment]
Hi @antonior0409, thanks, release version will not be available shortly, but you should be able to maven download this `1.1.0.M3`, as it's already publicly available. Or could you share the failure stacktrace?

**Comment by antonior0409** [comment]
Thanks for reply @sophiaso I'm using a private artifactory repo which not provide pre-release versions
