### ISSUE TITLE
Reading EventData properties in spring cloud stream binder

### ISSUE THREAD

**Issue by J4cku** [microsoft/spring-cloud-azure#509]
Is there any way to get properties of EventType using @StreamListener(Sink.INPUT) message handling?
I am only able to get the event type payload.

## Snapshot Code for Reproduce 
```java
@Slf4j
@EnableBinding(Sink.class)
public class EventhubSink {

  @StreamListener(Sink.INPUT)
  public void handleMessage(String payload, @Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer) {
    checkpointer.success().handle((r, ex) -> {
      if (ex == null) {
        log.info("checkpointed {}", payload);
      }
      return null;
    });
  }
}
```

**Comment by warrenzhu25** [comment]
Thanks for reporting this. Could you clarify your issue?
1. What do you mean exactly by `EventType`? Is this a custom header or property you passed in? If so, you can use `@Header("eventType") EventType eventType`

**Comment by J4cku** [comment]
Oh, I am sorry, I meant com.microsoft.azure.eventhubs.EventData (EventDataImpl).
My producer creates message using EventDataImpl - add some properties to it and then sends it to EventHub.
Then I've got two implementatrions:
1. Spring-cloud-stream-binder where I cannot get the properties out of the received message all I can get are Headers  and  paylod as either byte[] or Object(String)
2. azure-spring-messaging where in listener under  @AzureMessageListener I can work with full EventData object without any problems

**Comment by warrenzhu25** [comment]
Currently, event hub stream binder can't directly accept EventData like below: 
```
@StreamListener(Sink.INPUT)
  public void handleMessage(EventData eventData) {}
```

The design of binder is to decouple with specific message format such as EventData. If you just want to add some custom headers, you can use spring `Message`.

**Comment by saragluna** [comment]
No update on this issue, close it.
