### ISSUE TITLE
 how to set the receive mode to "RECEIVEANDDELETE" in spring cloud stream service bus binder

### ISSUE THREAD

**Issue by vnicers** [microsoft/spring-cloud-azure#511]
I see from the log that the default value of the receiver is PeekLock.
`c.m.azure.servicebus.MessageReceiver     : Creating MessageReceiver to entity 'xxx-topic/subscriptions/xxx-subscription', ReceiveMode 'PEEKLOCK'`
how to set the receiver to "ReceiveMode.RECEIVEANDDELETE" ?

**Comment by warrenzhu25** [comment]
Currently, setting `ReceiveMode.RECEIVEANDDELETE` is unsupported. But I want to understand the reason why you want to explicitly set this. From functional point, using this mode might cause message loss.

**Comment by vnicers** [comment]
@warrenzhu25 Our company intends to replace RabbitMQ with Service Bus in the production environment, so we used the Service Bus SDK and Spring Cloud Stream Binder for some performance tests, but using PeekLock mode found that the performance is much worse than RabbitMQ, so I want to try the RECEIVEANDDELETE mode again.

**Comment by pablosguajardo** [comment]
hello, could you see how to create the queue in "ReceiveMode.RECEIVEANDDELETE"?
I'm using an azure function developed with .net, from there it can be changed to "ReceiveMode.RECEIVEANDDELETE"?

**Comment by saragluna** [comment]
@pablosguajardo sorry for the late response. We've deprecated this repo, so I created an [issue](https://github.com/Azure/azure-sdk-for-java/issues/17421) there.
