### ISSUE TITLE
Is there any way to set “operationTime” in spring cloud stream service bus binder

### ISSUE THREAD

**Issue by ScottZhangZC** [microsoft/spring-cloud-azure#512]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
*   I Can control the “operationTime” by myself 

## Current Behavior
* When I use the service bus binder to send large amounts of data, it is easy to appear 'sent failed in async mode due to Send operation timed out ‘

## Possible Solution
*  set the  “operationTime”  option

## Branch
* placeholder

## Your Environment
* Operating System and version : Centos 7.5
* SDK version: spring-cloud-azure-servicebus-topic-stream-binder:1.1.0.RC5
spring-cloud-azure-servicebus-queue-stream-binder:1.1.0.RC5

**Comment by warrenzhu25** [comment]
Thanks for reporting this issue. What do you exactly by `OperationTime`? It could be:

1. The time sent one service bus message.
2. The time duration took by send operation

Another question is which control do you want for `OperationTime`? Setting a header or something else?

**Comment by ScottZhangZC** [comment]
1、I want to control the OperationTime, one or two minutes.
2、I Want to control the OperationTime in the configuration file, just like the configuration option "send-timeout" when sending synchronously.

Currently I can control the client's send timeout limit. When creating a QueueClient in the DefaultServiceBusQueueClientFactory.class, call the SetOperationTimeout() of the ConnectionStringBuilder object.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
