### ISSUE TITLE
AzureMessageListener does not open new traces with spring cloud sleuth

### ISSUE THREAD

**Issue by J4cku** [microsoft/spring-cloud-azure#513]
## Expected Behavior
I would expect @AzureMessageListener to open spans (spring cloud sleuth) when listening to Event Hub messages.

## Current Behavior
No spans/traces are opened

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
