### ISSUE TITLE
Incompatible Versions of EventHubClient when using azure-spring-boot-bom

### ISSUE THREAD

**Issue by pedrorlmarques** [microsoft/spring-cloud-azure#515]
Hi
In my maven project, I want to use spring-cloud-azure-eventhubs-stream-binder, and to import that I'm using the dependencyManagement azure-spring-boot-bom 2.1.6 to resolve the versions.

The problem is that when the dependency is imported it brings the version 1.0.0 of azure-eventhubs-1.0.0.jar. if I try to use this [sample](https://github.com/Microsoft/spring-cloud-azure/tree/release/1.1.0.RC5/spring-cloud-azure-samples/eventhubs-binder-sample) it throws this exception

`: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.microsoft.azure.eventhubs.EventHubClient.createSync(Ljava/lang/String;Ljava/util/concurrent/ScheduledExecutorService;)Lcom/microsoft/azure/eventhubs/EventHubClient;] with root cause

java.lang.NoSuchMethodError: com.microsoft.azure.eventhubs.EventHubClient.createSync(Ljava/lang/String;Ljava/util/concurrent/ScheduledExecutorService;)Lcom/microsoft/azure/eventhubs/EventHubClient;`

Workaround:

I delete the dependency management from the pom and import the dependency as-is and a new version of azure-eventhubs-2.2.0.jar came up and everything works as excepted.

**Comment by warrenzhu25** [comment]
`spring-cloud-azure-eventhubs-stream-binder` doesn't need `azure-spring-boot-bom`. It just needs `spring-cloud-azure-dependencies`. For detailed pom, please refer sample.

**Comment by pedrorlmarques** [comment]
Ok, I don't need but what if I use it, is this supposed to work or not?

**Comment by warrenzhu25** [comment]
If you need features from both `azure-spring-boot` and `spring-cloud-azure`, you can explicitly set the version. Otherwise, I suggest to just rely on `spring-cloud-azure`.
