### ISSUE TITLE
Support other auth options besides Auth file

### ISSUE THREAD

**Issue by xscript** [microsoft/spring-cloud-azure#520]
In Spring Cloud Stream Binder for Event Hub, only Auth file is supported as the auth option.
We should enable other auth options for users, since Auth file is not a GA feature in management SDK (https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md#using-an-authentication-file).

**Comment by warrenzhu25** [comment]
We support both auth file and connection string. Please refer https://github.com/Microsoft/spring-cloud-azure/tree/release/1.1.0.RC5/spring-cloud-azure-samples/eventhubs-binder-sample#connection-string-based-usage
