### ISSUE TITLE
No HealthIndicator implementation for event hub binder

### ISSUE THREAD

**Issue by TimoFreiberg** [microsoft/spring-cloud-azure#521]
## Expected Behavior
There is a HealthIndicator implementation that checks EventHub connectivity

## Current Behavior
There is no HealthIndicator implementation.
I tried writing a custom HealthIndicator that checks EventHub connectivity by verifying that
```kotlin
EventHubClient.createSync(connectionString, ScheduledThreadPoolExecutor(0)).close().get()
```
doesn't throw, but that succeeds when the SharedAccessKey is wrong - it only protects against more obvious errors.

## Possible Solution
Implement a HealthIndicator that verifies EventHub connectivity

## Steps to Reproduce (for bugs)
Not applicable

## Snapshot Code for Reproduce 
Not applicable

## Branch
master

## Your Environment
Not applicable

**Comment by warrenzhu25** [comment]
Thanks for reporting this. We'll evaluate this.

**Comment by ScottZhangZC** [comment]
I am also expecting this feature, and when will this feature be implemented?

**Comment by yaoyiyao** [comment]
Do we have a workaround to do health check?

**Comment by benweizhu** [comment]
Expect this feature

**Comment by djangofan** [comment]
There is a way to do it with Kafka:    @Autowired private KafkaStreams kafkaStreams;    in  a health check class, but I am not sure how you would do it with eventhubs binders.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
