### ISSUE TITLE
Spring Cloud Binder Event Hubs Error Channel Implementation is missing

### ISSUE THREAD

**Issue by Dharm19** [microsoft/spring-cloud-azure#522]
Spring Cloud Stream Binder create a dedicated error channel for each input binding to handle error message. Looks like this feature is not available in Event Hub Binder Implementation.

In case of any exception/error message will be lost, it should be passed to error handler and message should be moved configured topic/namespace.

https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#binder-error-channels

**Comment by warrenzhu25** [comment]
Thanks for reporting this. I think these are 3 feature requests. 
1. Support sending error into error channel.
2. Support auto retry from producer side. 
3. Support auto retry from consumer side.

We'll evaluate these features.

**Comment by benweizhu** [comment]
Has this feature been added?

**Comment by saragluna** [comment]
@benweizhu The error channel's been implemented, you could try it with our daily built snapshot.
