### ISSUE TITLE
Service Bus Binder Support Dead Letter Queue

### ISSUE THREAD

**Issue by chenghaoharvey** [microsoft/spring-cloud-azure#530]
Hi May i know that service bus binder support dead letter queue capability? We can use it to send exception msg to it?

**Comment by warrenzhu25** [comment]
As I know, no support for now. PR welcome

**Comment by avpines** [comment]
@warrenzhu25 are there any future plans to support it?

**Comment by chenghaoharvey** [comment]
@warrenzhu25 @saragluna  Refer to Rabbit Binder DLQ implementation, below capabilities should be included in Service Bus DLQ. Do you have any suggestions?
- Producer binds dedicated DLQ for MQ, Topic. 
- Consumer binds dedicated DLQ for MQ, Topic.
- Exception msg will fall into DLQ automatically.

**Comment by yiliuTo** [comment]
Thanks for the reporting, we will investigate it.

**Comment by chenghaoharvey** [comment]
May i have your response if you confirmed it? Or let me know if any PR is needed? Thanks

**Comment by warrenzhu25** [comment]
@chenghaoharvey feel free to send PR.

**Comment by chenghaoharvey** [comment]
I just want to get your comprehensive input/suggestion before development.

**Comment by yiliuTo** [comment]
Hi @chenghaoharvey , thanks for your suggestions on the capabilities of service bus DLQ. According to our investigation and comparison of service bus and MQ DLQ, we have the following ideas:
1. For the producer/consumer binds to dedicated DLQ of MQ: MQ will create DLQ with the property autoBindDlq, however, service bus creates DLQ automatically for each queue/subscription, thus I think there's no need to explicitly declare a DLQ for consumer/producer in binders.
2. Exception msg fall into DLQ: I agree with you on this feature, exceptions thrown from consumer clients are expected to be put into DLQ by binders.

Any further discussions and PRs are welcome.

**Comment by chenghaoharvey** [comment]
@yiliuTo 
The configuration "requeueRejected" for DLQ should be provided as like as Rabbit MQ, which the value means
1) true:  The msg, that triggers any exception in consumer, will be force to DLQ.
2)false: The several activities as showed in below link that cause message to be forced into DLQ

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues

**Comment by yiliuTo** [comment]
@chenghaoharvey I agree with you.

**Comment by chenghaoharvey** [comment]
Hi, when i deep dive service bus binder codes, i found that "requeueRejected" would be related to "checkpoint model".
1) if the checkpoint model is "REPORT", any exception message will be force to DLQ with requeueRejected value "true"
2)if the checkpoint model is "MANUAL", the requeueRejected should be unavailable and user can force any exception message to DLQ by checkpoint, such as "checkpoint.deadLetterQueue()"

Do you agree?
@yiliuTo

**Comment by chenghaoharvey** [comment]
@yiliuTo  The dlq was available for service bus queue. Could you please help to review the code and let me know if you have any concern. If not, i will complete the service bus topic and create PR.

**Comment by saragluna** [comment]
@chenghaoharvey we've recently deprecated this repo and sorry for the bad timing. Do you mind migrating this PR targeting our new [location](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-cloud-servicebus-queue-stream-binder)? If this is not acceptable then I'll apply these changes to my fork and you could proceed there. Please let me know your preference and sorry for the trouble.

**Comment by chenghaoharvey** [comment]
may i have your suggestions for below problem when "maven installing"  for "Microsoft Azure Java Core Library"

`[ERROR] java.method.parameterTypeParameterChanged: parameter reactor.util.retry.Retry reactor.util.retry.Retry::from(===java.util.function.Function<reactor.core.publisher.Flux<reactor.util.retry.Retry.RetrySignal>, ? extends org.reactivestreams.Publisher<?>>===): The type parameter of method parameter changed. The original type was 'java.util.function.Function<reactor.core.publisher.Flux<reactor.util.retry.Retry.RetrySignal>, org.reactivestreams.Publisher<?>>'while the new type is 'java.util.function.Function<reactor.core.publisher.Flux<reactor.util.retry.Retry.RetrySignal>, ? extends org.reactivestreams.Publisher<?>>'. (breaks semantic versioning) [io.projectreactor:reactor-core:jar:3.3.9.RELEASE]
[ERROR] java.method.finalMethodAddedToNonFinalClass: method reactor.util.retry.Retry reactor.util.retry.Retry::withThrowable(java.util.function.Function<reactor.core.publisher.Flux<java.lang.Throwable>, ? extends org.reactivestreams.Publisher<?>>): A final method has been added to an inheritable class. (breaks semantic versioning) [io.projectreactor:reactor-core:jar:3.3.9.RELEASE]`

**Comment by saragluna** [comment]
@chenghaoharvey sorry for the late response. Please follow this guideline to build from source in the new repo https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/CONTRIBUTING.md#building-from-source.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
