### ISSUE TITLE
Message processing continues despite user code exception for Event Hub

### ISSUE THREAD

**Issue by chadshowalter** [microsoft/spring-cloud-azure#540]
## Expected Behavior
The documentation for [Spring Cloud Azure Event Hub Stream Binder](https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-eventhubs-stream-binder) states that when using BATCH checkpoint mode (the default), 

> BATCH, checkpoints occur after each batch of messages successfully processed by user-defined message handler without any exception. default mode. You may experience reprocessing at most one batch of messages when message processing fails. Be aware that batch size could be any value.

My expectation, therefore, is that if an exception occurs in my code like this:
```java
    private volatile int cnt = 0;
    @StreamListener(value = Sink.INPUT)
    public void handleEverything(String message) {
        cnt++;
        if (cnt == 15) {
           throw new RuntimeException("BOOM!");
        }
    }
```
That message processing would stall when the 15th message is processed, and that no further messages would be processed, because the checkpointer would not commit the batch.
For example, if there are 50 unprocessed messages on the Event Hub in the above scenario, and we are getting the messages in batches of 10, I would expect that 10 messages would be processed, the checkpointer would commit, then no further commits would happen because the exception would be thrown in the middle of the 2nd batch (15th message). 
## Current Behavior
What actually happens is that the exception is simply logged by PartitionPump, and the checkpointer commits after the batch. Additionally, for RECORD mode the behavior is similar: the exception is logged, but processing continues (the checkpointer commits the messages after the exception).

What I would like is for no checkpoint commits to happen after the exception, so that messages aren't lost.  For example, if my applications saves the message to a database, and the database is briefly down, I don't want messages to be committed if an exception is thrown on save.  What is the recommended way to accomplish this?  

## Your Environment
* Version used: 1.1.0.RC5
* Operating System and version (desktop or mobile): OSX 10.14.5

**Comment by warrenzhu25** [comment]
Some suggestions here:
1.  Event hub is like Kafka, has multiple physical partitions. And checkpoint is based on offsets of each partition. So this means you only can claim all messages between certain offset has been successfully processed.
2. So if you want to implement at least once message consumption, you have several things to do:
   a. You have another place to hold failed messages, then you process these failed message in another pipeline. 
   b. You need to process messages sequentially for each partition, this will slow down the whole message processing speed.
   c. You can use manual checkpoint mode, then you process message concurrently, and you have full control of when to checkpoint message.

**Comment by chadshowalter** [comment]
You are right, I want to implement "at least once" consumption.  And I would like to use checkpointing to indicate that I've consumed all messages in a batch successfully.   If there are any failures when processing a batch, I would like to retry processing for that entire batch using some retry strategy, and not to checkpoint until the failed batch has been successfully processed.  I understand that "poison messages" could stall message processing with this approach, but I would handle this in the retry logic as necessary.

In looking at the EPH documentation [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-event-processor-host), I quote 

> The idea behind Event Hubs is that you get "at least once" delivery at great scale. By making your downstream systems idempotent, it is easy to recover from failures or restarts that result in the same events being received multiple times.

This is precisely what I would like to do.  However, it does not seem straightforward to achieve this with the Spring Cloud Azure Stream binder -- particularly, the "recover from failures" part.  One option, as you've said, is to use manual checkpoint mode, but this seems awkward since it doesn't expose event handling and checkpointing at a batch level.  Starting from the example [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send), it looks like I could easily write retry logic in the onEvents method in IEventProcessor that would do what I want -- but without some significant amount of additional code, I don't see how I could accomplish this with the stream binder.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
