### ISSUE TITLE
appconfiguration-config does not pick up proxy setting

### ISSUE THREAD

**Issue by liyubupt** [microsoft/spring-cloud-azure#541]
##  Expected Behavior
* The spring boot application can connect to Azure App Configuration with proxy setting configured as jvm options

## Current Behavior
* We have the error "Connection timed out: connect" while starting the spring boot application even though proxy setting is configured as jvm options

## Possible Solution
* Configure proxy setting for apache http client

## Steps to Reproduce (for bugs)
* Start spring boot application behind the proxy. 

## Your Environment
* Version used: 1.1.0.M3
* Windows and version (desktop):

**Comment by piizei** [comment]
I assume one would just need to change AzureConfigBootstrapConfiguration.java line 95 from createDefault() to createSystem() to fix this.

**Comment by liyubupt** [comment]
Is there any update? @saragluna :-)

**Comment by piizei** [comment]
Meanwhile I founded this: https://github.com/Azure/azure-sdk-for-java/blob/azure-data-appconfiguration_1.0.0-beta.7/sdk/appconfiguration/azure-data-appconfiguration/README.md

This has different client setup that looks like it could support proxies. I wonder why the Spring wrapper is not using this as the underlying connection?

**Comment by neuqlz** [comment]
Now, this issue has been fixed in the latest SNAPSHOT version.
