### ISSUE TITLE
China Azure Storage Account Access Issue in Springboot 

### ISSUE THREAD

**Issue by rajjav123** [microsoft/spring-cloud-azure#550]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
The Springboot application that read message from Event Hub should work in both US East and China East 

## Current Behavior
It is working fine in US East region . But in China East region , it is not able to connect to the China Storage account

## Possible Solution
I saw some references like , for China we need to specify a different URL for the Storage account . I see the following in the Enviornment.java
public enum Environment {
    GLOBAL("core.windows.net"),
    CHINA("core.chinacloudapi.cn");

I tried to set the following property in the application.properties :

spring:
 cloud:
    azure:
      environment: CHINA 
But it is not working . Still the environment is coming as GLOBAL . Am I setting the property correctly . 

## Snapshot Code for Reproduce 

Working property in US East : 
~~~yml
spring:
  cloud:
    azure:
      eventhub:
        connection-string: applicationconnectionstringvalue
        checkpoint-access-key: applicationcheckpointaccesskey
        checkpoint-storage-account: applicationstaorageaccountname
    stream:
      bindings:
        input:
          destination: eventhubname
          group: eventhubconsumergroup
~~~

Not working property in China East
~~~yml
spring:
  cloud:
    azure:
      environment: CHINA
      eventhub:
        connection-string: chinaapplicationconnectionstringvalue
        checkpoint-access-key: chinaapplicationcheckpointaccesskey
        checkpoint-storage-account: chinaapplicationstaorageaccountname
    stream:
      bindings:
        input:
          destination: chinaeventhubname
          group: chinaeventhubconsumergroup
~~~

## Branch
* placeholder

## Your Environment
Springboot version : 2.1.5

**Comment by warrenzhu25** [comment]
As I understand, you used `azure-spring-boot`. You should follow https://github.com/Microsoft/spring-cloud-azure/tree/release/1.1.0.RC5/spring-cloud-azure-samples/eventhubs-binder-sample. Any questions let me know.

**Comment by rajjav123** [comment]
Thanks for the reply.Yes . I am using the Azure spring boot .I am following the Connection String based usage . That is working perfectly fine in US East region .But with the same property set up, when I deploy the application in China East environment , I am getting Storage account time out exception . What I understood is , I need to set the environment as China in the application.properties for China East . I tried that .But still I am getting the same exception. I tried to set different values like China, CHINA .But no luck .

~~~yml
spring:
  cloud:
    azure:
      environment: CHINA
~~~

I am using the Stream binder version : 1.1.RC2 .Is that an issue ?

**Comment by warrenzhu25** [comment]
This property should work, could you provide detailed error message and stacktrace for troubleshooting? Thanks

**Comment by rajjav123** [comment]
Following is the Stack trace :  Please note that , I have removed the actual eventhub name , consumer group and host name from the last few lines of the error messages .  I have verified the Storage account name and access key multiple times to make sure that I am not giving any wrong storage account information.

[OUT] at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:242) ~[azure-storage-8.0.0.jar!/:na]
 [OUT] Caused by: java.util.concurrent.TimeoutException: The client could not finish the operation within specified maximum execution timeout.
 [OUT] at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_202]
 [OUT] at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[na:1.8.0_202]
 [OUT] at com.microsoft.azure.eventprocessorhost.PartitionManager.lambda$buildRetries$16(PartitionManager.java:225) [azure-eventhubs-eph-2.4.0.jar!/:na]
[OUT] at com.microsoft.azure.eventprocessorhost.PartitionManager.lambda$initializeStores$11(PartitionManager.java:185) [azure-eventhubs-eph-2.4.0.jar!/:na]
 [OUT] at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.createLeaseStoreIfNotExists(AzureStorageCheckpointLeaseManager.java:233) ~[azure-eventhubs-eph-2.4.0.jar!/:na]
 [OUT] at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:323) ~[azure-storage-8.0.0.jar!/:na]
 [OUT] at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:354) ~[azure-storage-8.0.0.jar!/:na]
 [OUT] at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:744) ~[azure-storage-8.0.0.jar!/:na]
[OUT] at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:243) ~[azure-storage-8.0.0.jar!/:na]
 [OUT] com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
 [OUT] [08-19-2019 02:44:26] [35m[[eventhubname|consumergroup|id]-1-3][0;39m [1;31mERROR[0;39m[c.m.a.e.AzureStorageCheckpointLeaseManager] - host hostname: Failure while creating lease store
 [OUT] [08-19-2019 02:44:32] [35m[[eventhubname|consumergroup||id]-1-9][0;39m [1;31mERROR[0;39m[c.m.a.e.AzureStorageCheckpointLeaseManager] - host hostname: Failure while creating lease store
 [OUT] com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout

**Comment by rajjav123** [comment]
I did some more debugging with the above property set up . I see that the Storage Connection string is created as EndpointSuffix=core.windows.net;AccountKey=storageaccountkey;DefaultEndpointsProtocol=https;AccountName=storageaccountname  in the AzureEventHubAutoConfiguration.java . The endpoint suffix is not getting set as "core.chinacloudapi.cn" eventhough I set the environment as China in application.properties.

**Comment by jialindai** [comment]
hi @rajjav123, which version are you using? Is it latest snapshot?

**Comment by rajjav123** [comment]
I am using the Stream binder version : 1.1.0.RC2  . Somehow , the environment property is not picked up .

I created a CustomEnvironmentProvider to override the property as follows .In that case , it is working fine.

~~~java
import com.microsoft.azure.spring.cloud.context.core.api.Environment;
import com.microsoft.azure.spring.cloud.context.core.api.EnvironmentProvider;
import org.springframework.stereotype.Component;

@Component
public class CustomEnvironmentProvider implements EnvironmentProvider {
    private Environment environment = Environment.CHINA;



    @Override
    public Environment getEnvironment() {
        return environment;
    }
}
~~~

**Comment by rajjav123** [comment]
Is there any difference between 1.1.0.RC2 and 1.1.0.RC5 in terms of handling the Azure Environment . Right now , we only have access to 1.1.0.RC2 within our org.

**Comment by rajjav123** [comment]
I am attaching one more finding while debugging . Even though I set the environment properties , the AzureProperties object is coming as NULL. So it is not setting the actual environment. 

![Capture](https://user-images.githubusercontent.com/54073936/63283722-fcd58e80-c27f-11e9-8f7f-7791f2c03207.PNG)

**Comment by jialindai** [comment]
On 1.1.0.RC2 version, the starter expects following properties:

spring.cloud.azure.credential-file-path
spring.cloud.azure.resource-group

When above properties are there, the environment will be picked up.

In your case, I think the workaround to provide one custom EnvironmentProvider is good.

**Comment by rajjav123** [comment]
Thanks @jialindai  . Is this issue addressed in 1.1.0.RC5 version?

**Comment by jialindai** [comment]
hi @rajjav123, the behavior is the same in 1.1.0.RC5.

**Comment by jialindai** [comment]
I am closing this issue. Let me know if you get further question.
