### ISSUE TITLE
spring-cloud-starter-azure-appconfiguration-config depends on Spring Framework milestone repository

### ISSUE THREAD

**Issue by chutch1122** [microsoft/spring-cloud-azure#551]
The latest version of `spring-cloud-starter-azure-appconfiguration-config` (`com.microsoft.azure:spring-cloud-starter-azure-appconfiguration-config:1.1.0.M3`) currently depends on `org.springframework.cloud:spring-cloud-dependencies-parent:2.1.0.RC3`. However, `2.1.0.RC3` is only available in the Spring Framework Milestones Maven repository.

If you use Maven as your dependency manager, this isn't an issue. However, if you use **Gradle** (as my team does) - you will have to include the Spring Framework Milestones Maven repository.

This is done by adding the repository to the project's `build.gradle` file. For example:
```
repositories {
	maven { url 'https://maven.springframework.org/milestone/' } // <-- This line is required to be able to resolve spring-cloud-dependencies-parent:2.1.0.RC3
	mavenCentral()
}
```

It would be great if the `com.microsoft.azure:spring-cloud-starter-azure-appconfiguration-config` package could depend on a version of `spring-cloud-dependencies-parent` that exists in Maven Central - especially since that is where `spring-cloud-starter-azure-appconfiguration-config` is located.

**Comment by neuqlz** [comment]
Hi:
 Thanks for your suggestions. Now we have updated the related dependencies to 2.1.2.RELEASE which aligns with Greenwich.RELEASE version of spring-cloud in the master. However, for our milestone and RC release, it’s possible that we will reference Spring’s milestone or RC version.
