### ISSUE TITLE
Possible to add refreshing secrets from the Key Vault through refresh event.?

### ISSUE THREAD

**Issue by sheekaat** [microsoft/spring-cloud-azure#559]
Nowadays, lot of projects are using Azure Key Vault for secrets management and adopting to the key rotation mandatorily. In such cases, it'd be helpful if the spring azure key vault supports refreshing the secrets through spring refresh event. If you've known an alternative without introducing additional components like Service Bus, Azure functions, then, let us know?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
