### ISSUE TITLE
Add Spring Cloud Stream Binder for Event Grid

### ISSUE THREAD

**Issue by emivaljr** [microsoft/spring-cloud-azure#560]
The Azure Event Grid(https://azure.microsoft.com/en-us/services/event-grid/) is available for a while now and it would be good if we had an implementation of Spring Cloud Stream Binder for Event Grid.

**Comment by saragluna** [comment]
@emivaljr Thanks for your feedback, we'll consider this feature.

**Comment by vchernogorov** [comment]
Any updates on this?

**Comment by saragluna** [comment]
@vchernogorov No, this feature is still in our backlog.

**Comment by sankar228** [comment]
Hi, do we have spring cloud functions supported on Event Grid events

**Comment by saragluna** [comment]
@sankar228 sorry for the late response. Which spring cloud functions are you referring to?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
