### ISSUE TITLE
What is the latest version for Spring Cloud Azure Event Hub Stream Binder?

### ISSUE THREAD

**Issue by benweizhu** [microsoft/spring-cloud-azure#564]
Spring Cloud Azure Event Hub Stream Binder

Where does this binder library host? I cannot find it on Maven.

**Comment by saragluna** [comment]
The latest version is 1.1.0.RC5.  Check it [here](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-cloud-azure-eventhubs-stream-binder%22), or [here](https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-azure-eventhubs-stream-binder).

**Comment by benweizhu** [comment]
There is a big difference between RC2 and RC5 and M2, RC2 include spring cloud stream, RC5 and M4 exclude it.

And If I try to include spring cloud stream myself. Then there is a error:

Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by benweizhu** [comment]
![image](https://user-images.githubusercontent.com/5471228/65745256-ae909680-e12d-11e9-881f-9d368249d669.png)

![image](https://user-images.githubusercontent.com/5471228/65745289-ca943800-e12d-11e9-9e68-f9f693dc4e92.png)

Any suggestion?
