### ISSUE TITLE
Could not download gradle spring-cloud-azure-eventhub-stream-binder dependencies

### ISSUE THREAD

**Issue by benweizhu** [microsoft/spring-cloud-azure#570]
Hi,

I found out we could not download spring-cloud-azure-eventhub-stream-binder dependencies version above RC2 in gradle,

For example, com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.1.0.RC3

But if I use the maven project, I can download them.

Here is an example
https://github.com/benweizhu/spring-cloud-azure-eventhubs-stream-binder-dependencies

There is a big change in POM between RC2 and RC3

https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-eventhubs-stream-binder/1.1.0.RC2/spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC2.pom

https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-eventhubs-stream-binder/1.1.0.RC3/spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC3.pom

The thing I see the difference between

https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-dependencies/1.1.0.RC2/spring-cloud-azure-dependencies-1.1.0.RC2.pom

https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-dependencies/1.1.0.RC3/spring-cloud-azure-dependencies-1.1.0.RC3.pom

In which, RC2 use a release version of spring-cloud-dependencies-parent

RC3 use 2.1.0.RC3 version, and all the version above RC3 is using 2.1.0.RC3.

```
 Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.1.0.M4.
     Required by:
         project :
      > Could not resolve com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.1.0.M4.
         > Could not parse POM https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-eventhubs-stream-binder/1.1.0.M4/spring-cloud-azure-eventhubs-stream-binder-1.1.0.M4.pom
            > Could not resolve com.microsoft.azure:spring-cloud-azure-stream-binder:1.1.0.M4.
               > Could not resolve com.microsoft.azure:spring-cloud-azure-stream-binder:1.1.0.M4.
                  > Could not parse POM https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-stream-binder/1.1.0.M4/spring-cloud-azure-stream-binder-1.1.0.M4.pom
                     > Could not resolve com.microsoft.azure:spring-cloud-azure:1.1.0.M4.
                        > Could not resolve com.microsoft.azure:spring-cloud-azure:1.1.0.M4.
                           > Could not parse POM https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure/1.1.0.M4/spring-cloud-azure-1.1.0.M4.pom
                              > Could not resolve com.microsoft.azure:spring-cloud-azure-dependencies:1.1.0.M4.
                                 > Could not resolve com.microsoft.azure:spring-cloud-azure-dependencies:1.1.0.M4.
                                    > Could not parse POM https://repo.maven.apache.org/maven2/com/microsoft/azure/spring-cloud-azure-dependencies/1.1.0.M4/spring-cloud-azure-dependencies-1.1.0.M4.pom
                                       > Could not find org.springframework.cloud:spring-cloud-dependencies-parent:2.1.0.RC3.
   > Could not find org.springframework.cloud:spring-cloud-dependencies-parent:2.1.0.RC3.

```

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies-parent

**Comment by benweizhu** [comment]
And BTW, How often does it lib release to maven repository?

**Comment by soleverlee** [comment]
same problem.
