### ISSUE TITLE
Service Bus Queue Stream Binder - Failed to introspect class BinderFactoryConfiguration

### ISSUE THREAD

**Issue by zpdeering** [microsoft/spring-cloud-azure#574]
I have been using spring-cloud-azure-servicebus-queue-stream-binder:1.1.0.M4 with Spring Boot 2.1.9.RELEASE without any issues. When I tried to update to Spring Boot 2.2.0.RELEASE, the application started throwing errors on initialization:

`ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/edu/jh/tic/precog/hl7/PrecogHL7ConsumerApplication.class]; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.stream.config.BinderFactoryConfiguration] from ClassLoader [ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@3e9b1010
]`

I'm assuming that some upstream dependency in Spring Cloud was changed, and that's why it can't load the BinderFactoryConfiguration. Is there a dependency that I would need to include?

**Comment by neuqlz** [comment]
Thanks for your feedback, we will inspect it later.

**Comment by saragluna** [comment]
@zpdeering Thanks for reporting this but I'm afraid that Spring-Cloud-Azure is not compatible with Spring Boot 2.2.0 now. We are planning a release that aligns with Spring Boot 2.2.x and Spring Cloud Hoxton next month.

**Comment by zpdeering** [comment]
Great, thanks for the info

**Comment by saragluna** [comment]
Closing this issue since Spring Cloud Azure 1.2.x has been released.

https://github.com/microsoft/spring-cloud-azure/releases
