### ISSUE TITLE
[Eventhubs] Is there a way to pause binders to receive messages and resume it?

### ISSUE THREAD

**Issue by benweizhu** [microsoft/spring-cloud-azure#577]
Hi there,

I am wondering is there a way to pause binders to receive messages and resume it?

Something like [6.6. Binding visualization and control](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_binding_visualization_and_control)

Thanks

**Comment by benweizhu** [comment]
Stop and Start seems working.

**Comment by neuqlz** [comment]
Very glad to hear that you make it work, close the issue.
