### ISSUE TITLE
AppConfiguration does not resolve linked keyvault secrets

### ISSUE THREAD

**Issue by J4cku** [microsoft/spring-cloud-azure#579]
## Expected Behavior
* when refferencing app configuration linked secret - resolve value from keyvault

## Current Behavior
* app configuration resolves secret as json value 
e.g.
`{
  "uri": "https://***-kv.vault.azure.net/secrets/test-secret/***"
}`
![config](https://i.imgur.com/8yhMYO9.png "App Config in Azure")

Using property as:
`@Value(${test-secret}) String testSecret`
resolves just fine, but that is not a workaround for me

## Your Environment
* Version used: spring-cloud-starter-azure-appconfiguration-config 1.1.0.M4, azure-keyvault-secrets-spring-boot-starter 2.1.7, spring boot 2.1.9
* Operating System and version (desktop or mobile): Windows
* SDK version:

**Comment by mrm9084** [comment]
@J4cku Have you tried using the snapshot version of App Configuration? The support for Key Vault References is there and will be in the next release. PR https://github.com/microsoft/spring-cloud-azure/pull/571 is adding an example of how to use Key Vault with App Configuration if you are interested in seeing how it is used. It walks you through converting an App that is using cosmosdb to one being managed by App Configuration using Key Vault References.

**Comment by J4cku** [comment]
@mrm9084 
It works well ;).
Just a quick question, will it be possible to set tenantId, clientId, clientSecret differently then with ENV variables?

**Comment by mrm9084** [comment]
@J4cku Currently we only support using a Service Principal or Managed Identity through Environment Variables. If you are interested in other methods of login or configuration please create a new issue and we can look into adding it. Also a new version has been released with Key Vault support.

```xml
<dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>spring-cloud-azure-appconfiguration-config</artifactId>
        <version>1.1.0.M5</version>
</dependency>
```
