### ISSUE TITLE
Support EventHub retry when failed?

### ISSUE THREAD

**Issue by yangwliu** [microsoft/spring-cloud-azure#582]
I found there is a class named "RetryPolicy" in the package of "com.microsoft.azure.eventhubs", but I don't find some sample and configuration for event hub retry, both sending and reciveing. So  the libary support event hub to retry or not when sending or consuming?

**Comment by yangwliu** [comment]
@neuqlz hey, what is going on for this problem?

**Comment by neuqlz** [comment]
Hi @yangwliu,
Sorry for the late response. Currently, the library support retries when sending, but not support retries when consuming. And also, RetryPolicy can't be set, the library will use the default retry policy to do retry.

**Comment by yangwliu** [comment]
@neuqlz, so do I need to set some configuration to open retry function?

**Comment by neuqlz** [comment]
@yangwliu there is no need to set configurations for it. Default RetryPolicy will be set into EventhubClient automatically.

**Comment by yangwliu** [comment]
@neuqlz  Thank you.

**Comment by vinceve** [comment]
@neuqlz What is the default retry policy? Is exposed in the stream binder to configure this?
