### ISSUE TITLE
Possibilty to specify checkpoint-storage-container-name

### ISSUE THREAD

**Issue by olialth** [microsoft/spring-cloud-azure#584]
## Expected Behavior
It should be possible to specify the checkpoint storage container name.

## Current Behavior
Currently, this is not possible. Therefore we cannot use event hub names with a dot in the name, as the EPH library tries to create storage container from event hub name (if no container name is set explicitly).

## Possible Solution
It should be possible to specify the checkpoint storage container name.

## Branch
* master

## Your Environment
* Version used:  1.1.0-SNAPSHOT
* Operating System and version (desktop or mobile): Linux
* SDK version:

**Comment by neuqlz** [comment]
@olialth Thanks for your feedback, we may consider adding this feature into our library in next release.

**Comment by warrenzhu25** [comment]
@olialth Good suggestion. This should be a simple change by add extra property. Could you send a pull request for this?

**Comment by saragluna** [comment]
This feature is implemented now. Check the sample here: https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/eventhubs-binder-sample#connection-string-based-usage. 

Closing this issue.
