### ISSUE TITLE
Can't use TimeCheckPointManager with eventhubs-stream-binder configs

### ISSUE THREAD

**Issue by dbachel2** [microsoft/spring-cloud-azure#585]
When using the com.microsoft.azure.eventhub.stream.binder

And Setting the following
spring.cloud.stream.eventhub.bindings.input.consumer:
    checkpointMode: TIME
    checkpointInterval: 60s

## Expected Behavior
Checkpoint Manager should be a TimeCheckpointManager recreating checkpoints at an interval of every 60 seconds

## Current Behavior
Lots of Null Pointer Exceptions because of line 40 in TimeCheckpointManager
BECAUSE line 72 of EventHubMessageChannelBinder does not SET the checkpoint Interval from the properties

## Possible Solution
* set checkpoint interval from the properties so that there will be no null exception

## Steps to Reproduce (for bugs)
set 
spring.cloud.stream.eventhub.bindings.input.consumer:
    checkpointMode: TIME
    checkpointInterval: 60s
in spring configs and then start up app connecting to a valid eventhub and storage account

## Branch
1.1.0.M5

## Your Environment
* Version used 1.1.0.M5
Java 11
Linux

**Comment by neuqlz** [comment]
Hi @dbachel2 
Thanks for pointing out that bug, I have fixed it in 1.1.0-SNAPSHOT. Related to this PR: #587

**Comment by neuqlz** [comment]
PR has been merged. Close the issue.
