### ISSUE TITLE
Should not auto configure the bean of EventHubConnectionStringProvider when app has not access to namespace level resource

### ISSUE THREAD

**Issue by benweizhu** [microsoft/spring-cloud-azure#586]
Hi,

According to the code in [AzureEventHubAutoConfiguration](https://github.com/microsoft/spring-cloud-azure/blob/84103956f31cabd235485a1f0069b9e8f8b9330b/spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubAutoConfiguration.java), it will try to auto-configure a bean [EventHubConnectionStringProvider](https://github.com/microsoft/spring-cloud-azure/blob/d79305ca4061ce4ffd9aacacd131207ed7f07bb0/spring-integration-azure/spring-integration-eventhubs/src/main/java/com/microsoft/azure/spring/integration/eventhub/factory/EventHubConnectionStringProvider.java)(code below) which tries to list all the AuthorizationRules from eventhub namespace level.

```
@Bean
    @ConditionalOnMissingBean
    public EventHubConnectionStringProvider eventHubConnectionStringProvider(
            AzureEventHubProperties eventHubProperties) {
        if (resourceManagerProvider != null) {
            EventHubNamespace namespace = resourceManagerProvider.getEventHubNamespaceManager()
                                                                 .getOrCreate(eventHubProperties.getNamespace());
            return new EventHubConnectionStringProvider(namespace);
        } else {
            String connectionString = eventHubProperties.getConnectionString();

            if (!StringUtils.hasText(connectionString)) {
                throw new IllegalArgumentException("Event hubs connection string cannot be empty");
            }

            TelemetryCollector.getInstance()
                              .addProperty(EVENT_HUB, NAMESPACE, EventHubUtils.getNamespace(connectionString));
            return new EventHubConnectionStringProvider(connectionString);
        }
    }
```

```
public EventHubConnectionStringProvider(@NonNull EventHubNamespace eventHubNamespace) {
        this(toConnectionString(eventHubNamespace));
    }

    private static String toConnectionString(EventHubNamespace eventHubNamespace) {
        return eventHubNamespace.listAuthorizationRules().stream().findFirst().map(AuthorizationRule::getKeys)
                                .map(EventHubAuthorizationKey::primaryConnectionString).orElseThrow(
                        () -> new EventHubRuntimeException(
                                String.format("Failed to fetch connection string of namespace '%s'",
                                        eventHubNamespace.name()), null));
    }
```

Since azure event hub allow you to control the authentication scope which can be different resource scope. Checkout here: [https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-azure-active-directory#resource-scope](https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-azure-active-directory#resource-scope) .

If the app is assign to eventhub or consumer group scope, then when auto configure this EventHubConnectionStringProvider bean, it will throw an exception says:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventHubConnectionStringProvider' defined in class path resource [com/microsoft/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.integration.eventhub.factory.EventHubConnectionStringProvider]: Factory method 'eventHubConnectionStringProvider' threw exception; nested exception is com.microsoft.azure.management.eventhub.ErrorResponseException: Status code 403, {"error":{"code":"AuthorizationFailed","message":"The client '8edc1b17-c378-488d-a1ac-2c346d299d12' with object id '8edc1b17-c378-488d-a1ac-2c346d299d12' does not have authorization to perform action 'Microsoft.EventHub/namespaces/AuthorizationRules/listKeys/action' over scope '/subscriptions/59265ccc-85ad-4fbe-828a-2bb4199cd22f/resourceGroups/inventory-ADD/providers/Microsoft.EventHub/namespaces/ids-eventhub/AuthorizationRules/RootManageSharedAccessKey' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

Is there a way to fix this? or any workaround for now?

Thanks,
Benwei

**Comment by saragluna** [comment]
Thanks for reporting this issue. In this case, the app has no access to the namespace which makes the code fail. Do you already have the connection string?

**Comment by benweizhu** [comment]
Do you mean if we already have the connection string, we should directly use the connection string?

We are thinking about custom our own EventHubConnectionStringProvider. Because the current code will get the RootManageSharedAccessKey's primary connection string from the namespace level.

What do you think?

**Comment by saragluna** [comment]
I'm not familiar with EventHub access control. If you don't have access to the namespace level, is there any way to retrieve the connection string? 

Since the code does not work correctly in your case, the possible workaround is to customize your own EventHubConnectionStringProvider.

**Comment by warrenzhu25** [comment]
@benweizhu The better way should be adding a config to support user to pass the shared key name. By for now, maybe you can try to implement your own EventHubConnectionStringProvider as primary spring bean.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
