### ISSUE TITLE
spring-cloud-starter-azure-eventhub releases missing on maven central

### ISSUE THREAD

**Issue by riddy** [microsoft/spring-cloud-azure#589]
## Expected Behavior
* Reference most current release: 1.1.0.RC5

>                     <groupId>com.microsoft.azure</groupId>
>                    <artifactId>spring-cloud-azure-starter-eventhub</artifactId>

## Current Behavior
* last version on maven central is 1.1.0.RC1

## Possible Solution
* update maven central 

## Steps to Reproduce (for bugs)
* see: https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-starter-azure-eventhub/1.1.0.RC1 

## Question
* will there be a stable release soon?

**Comment by riddy** [comment]
could it be that you renamed the artifact?

to: 

        <artifactId>spring-cloud-starter-azure-eventhubs</artifactId>

**Comment by neuqlz** [comment]
There will be a stable release soon and we have no plan to release 1.1.0.RC5 of spring-cloud-starter-azure-eventhub.  And we indeed renamed the artifact to spring-cloud-starter-azure-eventhubs. You can use it.
