### ISSUE TITLE
Spring Cloud Stream Binder - which versions correspond to which Spring Boot version

### ISSUE THREAD

**Issue by hirowla** [microsoft/spring-cloud-azure#595]
Hi, I'm trying to work out which version of "Spring Cloud Stream Binder for Azure Service Bus Queue" I should be using for application. My application is current using Spring Boot 2.1.11.

- Is 1.2.0 meant to be compatible with both Spring Boot 2.1 and 2.2?
- Should I be using the 1.2.0 version, or the 1.1.0.M6 version?
- If I'm supposed to be using 1.1.0.M6 version, is there a timeline for a release version (like it seems to be for 1.2.0)?

Thanks.

**Comment by saragluna** [comment]
Thanks for bringing this up. 1.2.0 is aligned with Spring  Cloud Hoxton, which is built on Spring Boot 2.2.x, so it's compatible with Spring Boot 2.2.  So please use 1.1.0.M6 if you're using Spring Boot 2.1.x. As for the timeline for the release, we don't have it yet, so please stay tuned.
