### ISSUE TITLE
azure-sdk-for-java VS azure-spring-boot VS spring-cloud-azure

### ISSUE THREAD

**Issue by Tetradeus** [microsoft/spring-cloud-azure#597]
I am lost between Microsoft Azure Java libraries ....

Why do we have both azure-spring-boot and spring-cloud-azure ? 
If I want storage as spring resource I have to use spring-cloud-azure but under the hood it uses a very old version azure-storage-6.1.0.jar (Nov 01, 2017) 

If I want to use azure-spring-boot (this is where we arrive if we follow https://cloud.spring.io/spring-cloud-azure), I do not have storage as a spring resource integration and behind the hood it uses the not recommened version ﻿﻿﻿﻿﻿azure-storage-blob-10.5.0.jar (https://github.com/Azure/azure-storage-java)

If I want to use the recommended version of the last azure storage sdk (v12), I have no spring integration at all (https://azure.microsoft.com/en-us/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/).

I can still see releases on all these projects. What are the plans ? What should we use ? 

Thanks for your help/directions.

**Comment by saragluna** [comment]
Thanks for reaching out to us and sorry for all the confusion. 

The difference between azure-spring-boot and spring-cloud-azure lies in that azure-spring-boot brings a Spring Boot starter, for auto-configure and managing dependency, while spring-cloud-azure provides Spring Resource integration. 

We're planning to upgrade underlying Azure Storage SDK to v12, for both projects, so please stay tuned.

**Comment by Tetradeus** [comment]
Hi @saragluna, thank you for your answer. 
Here are my 2 cents : 
- I am not sure that 2 different libs are bringing any benefits here but I may be wrong. It makes it more difficult for you to manage/maintain/upgrade and it brings confusion. Moreover, because dependencies are not the same it makes it almost impossible to use together.  
-  I think I saw that azure-spring-boot is bringing a lots of azure dependencies even when we are just interested in a small subset like storage, but maybe you started doing smaller specialized starter.
- Maintaining dependencies up to date is really important to make it useful and secure.

I hope it gets better in the future. Thanks.

**Comment by miva2** [comment]
I have been researching all day yesterday and am equally confused as @Tetradeus. 

In the end I settled on using `spring-azure-starter-storage` [following the approach described here](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage) as it most closely resembles what we want.

I could probably also use `azure-storage-spring-boot-starter` to achieve the same with probably more work.

**Comment by neuqlz** [comment]
@miva2 yep, as for storage, these two starters have the same effect. You can use any one of them according to your situation.

**Comment by saragluna** [comment]
We're migrating our projects to [azure-sdk-for-java repo](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring). The migration for [azure-spring-boot project](https://github.com/microsoft/azure-spring-boot) is done and spring-cloud-azure is still in process.

We deprecated the https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-storage and further development will be focused on https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-starters/spring-starter-azure-storage.

Closing this issue now.
