### ISSUE TITLE
Move mockito extension to test resources in spring-cloud-azure-appconfiguration-config

### ISSUE THREAD

**Issue by kubav182** [microsoft/spring-cloud-azure#602]
## Expected Behavior
/resources/mockito-extensions/org.mockito.plugins.MockMaker should be under src/test folder

## Current Behavior
/resources/mockito-extensions/org.mockito.plugins.MockMaker is under src/main folder

## Possible Solution
Move folder to test resources

## Steps to Reproduce (for bugs)
Use SpyBean annotation in test with Spring Boot and it will fail. Library should not turn on Mockito extension for other projects as it can cause test failing.

## Branch
1.1.0

## Your Environment
* Version used: 1.1.0

**Comment by mrm9084** [comment]
Hi @kubav182. I will get this update in my next PR. Thanks for the input.

**Comment by mrm9084** [comment]
Folder has been moved closing issue.
