### ISSUE TITLE
target folder should not be generated under the project root directory

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-cloud-azure#61]
## Expected Behavior
* No target folder generated for project root

## Current Behavior
* target folder 

## Branch
* master

## Your Environment
Not related with environment

**Comment by Incarnation-p-lee** [comment]
this target folder is generated by
`<artifactId>maven-checkstyle-plugin</artifactId>`.
As the plugin output and cache, which set by ${project.build.directory} by default. I think we can put it here as checkstyple output here.
