### ISSUE TITLE
Allow for custom MessageHandlerOptions and SessionHandlerOptions when creating a ServiceBusTemplate

### ISSUE THREAD

**Issue by JaapOudejans** [microsoft/spring-cloud-azure#612]
## Expected Behavior
* Control settings in the MessageHandlerOptions and SessionHandlerOptions classes when creating a ServiceBusTemplate. 

## Current Behavior
* The only way to configure these is by creating a custom ServiceBusTemplate implementation class or you will have the rely on the default settings in the MessageHandlerOptions and SessionHandlerOptions classes.

```java
        ServiceBusTopicTemplate template = new ServiceBusTopicTemplate(clientFactory) {
            @Override
            protected MessageHandlerOptions buildHandlerOptions() {
                return new MessageHandlerOptions(/* custom configuration here */);
            }

            @Override
            protected SessionHandlerOptions buildSessionHandlerOptions() {
                return new SessionHandlerOptions(/* custom configuration here */);
            }
        };
```

## Possible Solution
* Add setters for the MessageHandlerOptions and SessionHandlerOptions options and use them instead if they are provided. If they are null, simply build them with the defaults already provided.

```java
public class ServiceBusTemplate<T extends ServiceBusSenderFactory> implements SendOperation {

    protected MessageHandlerOptions messageHandlerOptions;

    ...

    public MessageHandlerOptions setMessageHandlerOptions(MessageHandlerOptions messageHandlerOptions) {
        this.messageHandlerOptions = messageHandlerOptions;
    }

    ...

    protected MessageHandlerOptions buildHandlerOptions() {
        if (messageHandlerOptions != null ) {
            return messageHandlerOptions;
        }
        return new MessageHandlerOptions(this.clientConfig.getConcurrency(), false, Duration.ofMinutes(5));
    }

    ...
}
```

You could do the same for the ExecutorService if you wanted to.

## Branch
* placeholder

## Your Environment
* Dependency: spring-integration-servicebus
* Version: 1.2.1

**Comment by saragluna** [comment]
Sorry for the late response, and we'll consider this feature.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
