### ISSUE TITLE
Feature management no real time sync with features in Azure.

### ISSUE THREAD

**Issue by ngara78** [microsoft/spring-cloud-azure#615]
**spring-cloud-azure-feature-management**

## Expected Behavior
* When features changes their values in Azure Feature Manager, a spring boot up quering them should get the latest.

## Current Behavior
* The values receive on Spring boot application start up, are the only ones available at all time.

## Snapshot Code for Reproduce 
```java
private final FeatureManager featureManager;

public Map<String, Boolean> getAllFlags() {
return featureManager.getFeatureManagement().getOnOff();
}
```
## Your Environment
* Version used: 1.1.0.M6
* Spring boot: 2.2.0.RELEASE
* SDK version: 11

**Comment by mrm9084** [comment]
@ngara78 In the M6 version refresh isn't on by default have you enabled refresh? See: https://github.com/microsoft/spring-cloud-azure/tree/release/1.1.0.M6/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config#supported-properties. spring.cloud.azure.appconfiguration.watch.enabled needs to be enabled.

**Comment by ngara78** [comment]
Thanks! It was not clear to me the purpose of watch.
