### ISSUE TITLE
No public method to query all flags.

### ISSUE THREAD

**Issue by ngara78** [microsoft/spring-cloud-azure#616]
**spring-cloud-azure-feature-management.**

There is no public method to query all flags in the latest version.

## Your Environment
Version used: 1.2.1
Spring boot: 2.2.0.RELEASE
SDK version: 11

**Comment by mrm9084** [comment]
Hi @ngara78, It wan't the intent of feature management to return all current values as the conditional values can return different values per request or over time. I am unsure of your use case, but would a method to get a list of all features names work for you?  Thanks for the input.

**Comment by ngara78** [comment]
Hi @mrm9084, we need to propagate the current status of the flags to other services that can't be connected to AppConfiguration. Easiest for our use case is a method returning the map "flag_name:current_value",but anything returning all Feature objects will work as well.

**Comment by lisaguthrie** [comment]
Hi @ngara78 - can you help me understand your scenario with services that can't be connected to App Config? We are preparing a preview of Private Link, which will allow you to securely connect to App Config on an isolated network -- will that help your scenario, or will you still be unable to connect those services? Feel free to reach out to me directly at lisa.guthrie@microsoft.com if you'd prefer not to discuss out here on GitHub. Thanks!

**Comment by ngara78** [comment]
Hi @lisaguthrie! Thanks for the hint, anyways our current limitation is "impose" by some company internal rules, so we will not be able to connect to the App Config anyways. Cheers!
