### ISSUE TITLE
AzureServiceBusQueueAutoConfiguration should add additional @ConditionalOnClass

### ISSUE THREAD

**Issue by jialindai** [microsoft/spring-cloud-azure#623]
Today AzureServiceBusQueueAutoConfiguration has @ConditionalOnClass(QueueClient.class), it should also add @ConditionalOnClass(ServiceBusQueueClientFactory.class)

This is because:
- QueueClient is in azure-servicebus
- ServiceBusQueueClientFactory is used in the configuration implementation and is in spring-integration-servicebus

Adding this avoid configuration error when spring-integration-servicebus is not in classpath

**Comment by neuqlz** [comment]
Thanks for pointing out that vulnerable codes, I have created a PR to handle it. #624

**Comment by neuqlz** [comment]
The PR has been merged into the mater. Now close the issue.
