### ISSUE TITLE
What are the default retry properties for handling error messages etc for the ServiceBus Queue binder

### ISSUE THREAD

**Issue by hirowla** [microsoft/spring-cloud-azure#628]
What are the default retry parameters for the Cloud Stream binder for Service Bus Queue? For example, how long does it wait before retrying a bad message.

I'm using the 1.1.1 version of the binder if that matters (it might be common for other versions).

**Comment by saragluna** [comment]
Which side do you mean, the producing side or consuming side? The Service Bus library contains a default retry policy when sending messages. And on the consuming side, spring offers to config using [RetryTemplate ](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_retry_template). However, the binder now has not implemented leveraging that RetryTemplate.

**Comment by hirowla** [comment]
I was thinking about the consuming side.

**Comment by saragluna** [comment]
We're considering implementing this feature, please stay tuned.

**Comment by avpines** [comment]
> Which side do you mean, the producing side or consuming side? The Service Bus library contains a default retry policy when sending messages. And on the consuming side, spring offers to config using [RetryTemplate ](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_retry_template). However, the binder now has not implemented leveraging that RetryTemplate.

What is the default retry policy for sending messages? I would like to know how I can handle the error in the spring-cloud-azure-servicebus-queue-stream-binder?

**Comment by hirowla** [comment]
I was wondering how this was going? I'm still running version 1.1.1 but is this part of 1.1.3 or later (particularly the consuming side)? Is there a current value which is hardcoded (like 1 minute or similar)?

**Comment by avpines** [comment]
Any update on this?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
