### ISSUE TITLE
@FeatureGate annotation does not work together with @PostMapping

### ISSUE THREAD

**Issue by michaelegner** [microsoft/spring-cloud-azure#629]
spring-cloud-azure-feature-management

## Expected Behavior
* If the feature is deactivated, it returns a 404 status code to the client with no response body

## Current Behavior
* When @FeatureGate annotation is used together with @PostMapping the default fallback is routed to a GET and does not return a 404 by default. As a workaround I had to add a fallback and an addional @GetMapping method to return a 404 status code. Is there a way to use @FeatureGate together with @PostMapping without adding addional GET methods? 

## Snapshot Code for Reproduce 
```java
@RequestMapping("/api/")
public class SomeController {
   ...
    @FeatureGate(feature = "SOME_FLAG", fallback = "somePath")
    @PostMapping(path = "somePath", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity someMethod(...) {
	    ...
        return ResponseEntity.created(location).build();
    }

    @GetMapping(path = "somePath", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity featureDeactivated() {
        return ResponseEntity.notFound().build();
    }
```

## Your Environment
* Version used: 1.2.1
* Spring boot: 2.2.4.RELEASE
* SDK version: 11

**Comment by mrm9084** [comment]
Hi @michaelegner I am looking into it, but it seems like a bug.

**Comment by mrm9084** [comment]
@michaelegner A new release of feature management just went out that should fix this issue.

**Comment by michaelegner** [comment]
Many thanks for the quick fix! We will check it out.
