### ISSUE TITLE
Allow usage of Event Hub based Cloud streaming w/o Storage account

### ISSUE THREAD

**Issue by JMayrbaeurl** [microsoft/spring-cloud-azure#650]
## Expected Behavior
* Sending events to Event Hub with Spring Cloud streaming without the need to create or provide an existing Azure storage account

## Current Behavior
* Even when just sending events a storage account has to be provided in the configuration

## Possible Solution
* Remove required storage account configuration in application.properties file. Just sending events to Event Hub doesn't need a storage account. The storage account, used for the checkpoints, should only be necessary for consuming events with EventHubProcessorHost

## Steps to Reproduce (for bugs)
* In application.properties configuration file simply remove the line starting with 'spring.cloud.azure.eventhub.checkpoint-storage-account'
* Launch Spring boot application with configured Event Hub Cloud streaming
* ...

## Branch
* master

## Your Environment
* Version used: Java 1.8
* Operating System and version (desktop or mobile): Windows 10 Enterprise (latest)
* SDK version: spring-cloud-azure-eventhubs-stream-binder 1.2.2 with Spring Boot 2.2.5.RELEASE

**Comment by saragluna** [comment]
Thanks for reaching out. Do you mean the case that when the application worked as a producer of messages?

**Comment by JMayrbaeurl** [comment]
@saragluna Yes. For applications that are just working as producer of messages, but never consumes any.

**Comment by saragluna** [comment]
@JMayrbaeurl 

Thanks for bringing this up and we'll consider this feature.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
