### ISSUE TITLE
Spring Boot app with Azure App Configuration - doesn't work behind corporate firewall / doesn't pick proxy settings

### ISSUE THREAD

**Issue by JJustas** [microsoft/spring-cloud-azure#656]
## Current Behavior / Steps to reproduce

I have created simple Spring Boot app with Azure App Configuration lib according to [Create a Java Spring app with Azure App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app). I use `Spring Boot v2.2.5.RELEASE` and

```
    <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>spring-cloud-azure-appconfiguration-config</artifactId>
        <version>1.2.2</version>
    </dependency>
```

When I try to run the app, console outputs logo and version:

```
    /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
    ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
     \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
      '  |____| .__|_| |_|_| |_\__, | / / / /
     =========|_|==============|___/=/_/_/_/
     :: Spring Boot ::        (v2.2.5.RELEASE)
```

It stops for a few mins and then throws:

```
    java.lang.RuntimeException: Max retries 12 times exceeded. Connection timed out: no further information: appconfigtest.azconfig.io:ip_address:443
    
    ...
    
    Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: appconfigtest.azconfig.io:ip_address:443
    Caused by: java.net.ConnectException: Connection timed out: no further information
```

Configured proxy settings using VM args (-Dhttps.proxyHost, -Dhttps.proxyPort, -Dhttp.nonProxyHosts), it gives effect for other sites but for this case didn't help.

When I try access the same App Config from the same machine using Azure CLI, .NET Core, Azure Functions in .NET core, it works well and displays the values. If I deploy the same Spring Boot app to the cloud, it also works well.

## Possible Solution

The issue seems to be the same as [appconfiguration-config does not pick up proxy setting](https://github.com/microsoft/spring-cloud-azure/issues/541). However, I use the latest library but the problem still exists.

**Comment by mssfang** [comment]
@JJustas  what is the connection type you are using? We have been looking at the issue.

**Comment by mssfang** [comment]
SDK provided a way to setup the proxy options when building a client. I created a PR that shows the sample for how to use it. https://github.com/Azure/azure-sdk-for-java/pull/10097

**Comment by JJustas** [comment]
Thanks but it should pick proxy settings automatically if any provided - it would be more convenient and save time for others.

**Comment by mssfang** [comment]
Azure Core 1.2.3 has support it already. (the latest App Config SDK 1.1.1 use Azure Core 1.2.3)
We support (https://azure.github.io/azure-sdk/general_azurecore.html#environment-variables)
- HTTP_PROXY // Proxy for HTTP connections
- HTTPS_PROXY // Proxy for HTTPS connections
- NO_PROXY // Hosts which must not use a proxy

and (https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/ProxyOptions.java#L52)
- https.proxyHost, 
- https.proxyPort 
- http.nonProxyHosts 
```
private static final List<Function<Configuration, ProxyOptions>> ENVIRONMENT_LOAD_ORDER = Arrays.asList(
    configuration -> attemptToLoadAzureProxy(configuration, Configuration.PROPERTY_HTTPS_PROXY),  //HTTPS_PROXY
    configuration -> attemptToLoadAzureProxy(configuration, Configuration.PROPERTY_HTTP_PROXY),  //HTTP_PROXY
    configuration -> attemptToLoadJavaProxy(configuration, HTTPS),  //Java https.*
    configuration -> attemptToLoadJavaProxy(configuration, HTTP)  //Java http.*
);
```
as well.

**Comment by mrm9084** [comment]
@JJustas In version 1.2.5 you are now able to set up proxy info. See https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config#client-builder-customization for details.

**Comment by MrOstling** [comment]
We are having a similar issue with using Evenhub behind a corporate firewall. It seems that I can set the proxy information via the configuration once I update to com.azure:azure-messaging-eventhubs:5.1.0, but I can't seem to figure out how to set the transportType to AmqpWebSockets. This causes an exception.  It appears that DefaultEventHubClientFactory creates new EventHubClientBuilders and doesn't have a mechanism to set the transporType. If someone could add transportType to the AzureEventHubProperties and pass it along to the clientBuilders through the clientFactory that might solve the issue. 

I was having trouble overwriting the clientFactory bean in our application to do this very thing. It seems that AzureEventHubAutoConfiguration is forcibly imported in EventHubBinderConfiguration which prevents our bean from being used. For some reason when we duplicate EventHubBinderConfiguration in our app to resolve the bean issue we loose the ability to publish/read from multiple eventhub namespaces.

**Comment by yiliuTo** [comment]
@MrOstling, we have opened a new issue for your problem, and you can follow it #702 up.

**Comment by mrm9084** [comment]
Is fixed as of version 1.x.5. Let us know if their are any additional issues.
