### ISSUE TITLE
spring-cloud-azure-appconfiguration-config-web is broken with azure-core:1.3.0

### ISSUE THREAD

**Issue by gandhirajan** [microsoft/spring-cloud-azure#659]
We were using spring-cloud-azure-appconfiguration-config-web:1.2.2 and azure-storage:8.6.0 to connect to app config and datalake respectively in our JAVA application.

After updating the new datalake dependency azure-storage-file-datalake:12.0.1 which internally uses azure-core:1.3.0, appconfiguration connectivity is broken. Getting the following exception:

> java.lang.RuntimeException: Failed to deserialize 5-parameter response without decoded headers.
> 	at com.azure.core.http.rest.ResponseConstructorsCache.lambda$invoke$2(ResponseConstructorsCache.java:132)
> 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4110)
> 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
> 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
> 	at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1747)
> 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:326)
> 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onComplete(MonoCacheTime.java:351)
> 	at reactor.core.publisher.Operators.complete(Operators.java:135)
> 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
> 	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
> 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)
> 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
> 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705)
> 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320)
> 	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337)
> 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705)
> 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
> 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
> 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
> 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
> 	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
> 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
> 	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
> 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705)
> 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
> 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
> 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
> 	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:419)
> 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:209)
> 	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:367)
> 	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
> 	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
> 	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:585)
> 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
> 	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1231)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1268)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> 	Suppressed: java.lang.Exception: #block terminated with an error
> 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
> 		at reactor.core.publisher.Mono.block(Mono.java:1664)
> 		at com.microsoft.azure.spring.cloud.config.stores.ClientStore.listSettings(ClientStore.java:123)
> 		at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.initProperties(AppConfigurationPropertySource.java:126)
> 		at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.create(AppConfigurationPropertySourceLocator.java:206)
> 		at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.addPropertySource(AppConfigurationPropertySourceLocator.java:139)
> 		at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.locate(AppConfigurationPropertySourceLocator.java:92)
> 		at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
> 		at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
> 		at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:101)
> 		at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)

**So I m unable to use spring-cloud-azure-appconfiguration-config-web:1.2.2 with latest azure-core:1.3.0 which seems to be a blocker for me. Any thoughts?**

**Comment by mrm9084** [comment]
@gandhirajan App Configuration uses Azure Core, but still uses version 1.2.0. We will be updating in our next release which should be in the next week. I will take a look into it to see if there is anything that can be done in the mean time.

**Comment by gandhirajan** [comment]
@mrm9084 Hi Matt, Thanks for your quick response. Please do let us know once the release is out next week so that we can test it out. This fix is crucial for everyone using AppConfig with latest version of Azure core. So I request you consider this issue on priority. Thanks in advance.

**Comment by saragluna** [comment]
@gandhirajan 

We've made a release yesterday including upgrading Azure Core to 1.3.0. Try with [release 1.2.3](https://github.com/microsoft/spring-cloud-azure/releases/tag/1.2.3) or [release 1.1.3](https://github.com/microsoft/spring-cloud-azure/releases/tag/1.1.3).

**Comment by gandhirajan** [comment]
@saragluna  @mrm9084  Hi Xiaolu and Matt, works as expected but we need to ensure that datalake dependency is added first before the app config dependency in pom.xml Thanks again. Closing the issue.
