### ISSUE TITLE
ASB message system properties retrieval.

### ISSUE THREAD

**Issue by AsetK** [microsoft/spring-cloud-azure#671]
## Expected Behavior
When using Spring Cloud Stream with Azure Service Bus Spring Integration can retrieve ASB message system properties from Spring Message entity. For example system "To" property.

## Current Behavior
Can't tretrieve ASB message system properties from Spring Message entity. For example system "To" property. Looks like ServiceBusMessageConverter do not forward some system properties.

**Comment by saragluna** [comment]
Thanks for reporting this issue and we'll look into it.

**Comment by AsetK** [comment]
Hi, any update?

**Comment by saragluna** [comment]
@AsetK, sorry for the late response and we're adding this to our feature list now, so please stay tuned. In the meantime, PR is welcome :-).

**Comment by saragluna** [comment]
@AsetK 
As we're considering adding some system properties into the header, could you help share your scenario, like where / how to use these headers, to help us decide which headers to include?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
