### ISSUE TITLE
App config 429 error for 400 keys for standard tier app config store

### ISSUE THREAD

**Issue by Karthickramk** [microsoft/spring-cloud-azure#672]
## Expected Behavior
App config property should be loaded properly

## Current Behavior
Our Azure App config store pricing tier: Standard
* in out application we have around 400 keys in azure app config and 20 pods are running.

bootstrap.yaml
spring:
  cloud:
    azure:
      appconfiguration:
        cache-expiration: 60000

We see 429 -  too many requests errors from app config. Because of this application does not load the latest config.

For 400 keys, how many requests will be fired to app config?

## Your Environment
* Version used: 1.2.3
* Operating System and version (desktop or mobile): 
* SDK version: java 11

**Comment by mrm9084** [comment]
@Karthickramk In the latest release 1.2.4 we have updated how some requests are done to reduce the overall number, which should help with 429. Please check it out and see if it helps.

**Comment by Karthickramk** [comment]
Thanks @mrm9084

**Comment by saragluna** [comment]
@Karthickramk Please try with 1.2.5 cause we missed something in the release 1.2.4.

**Comment by Karthickramk** [comment]
@saragluna  We upgraded to 1.2.5 and found that lesser calls are going to app config.

**Comment by saragluna** [comment]
Does it solve your problem? Could this issue be closed now？

**Comment by Karthickramk** [comment]
Yeah. We can close this.
