### ISSUE TITLE
[question][service bus] Current state against java sdk

### ISSUE THREAD

**Issue by bilak** [microsoft/spring-cloud-azure#689]
Hello,
we are starting new project. As mentioned [here](https://github.com/Azure/azure-service-bus-java) library is moved to [sdk](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus) and sdk has currently only [beta version](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-messaging-servicebus_7.0.0-beta.1). So my question is is this going to be implemented here in `spring-cloud-azure` project? Do we have to start with older version an will there be some migration guide to newer version?

Thanks

**Comment by saragluna** [comment]
Which module of Service Bus do you want to use? We're planning to upgrade our service bus SDK to track2 (the [one](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus) in the azure-sdk-for-java repo) later.

**Comment by bilak** [comment]
well I want to use quue/topic so probably amqp. Or are we talking here about other modules?
What does mean track2 later?

**Comment by saragluna** [comment]
Sorry for the late response. Are you going to use the Service Bus directly or use the Spring integration?

**Comment by bilak** [comment]
@saragluna we'd like to use spring integration

**Comment by saragluna** [comment]
So we'll also upgrade the underlying Service Bus SDK once they got a released version.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
