### ISSUE TITLE
small typo in the docs, property name is sessionsEnabled

### ISSUE THREAD

**Issue by leassis** [microsoft/spring-cloud-azure#698]
This is very simple but leads to a few minutes of a resource. In documentation says that the property is named as sessionEnabled but the real name is sessionsEnabled (session in plural)

**Comment by yiliuTo** [comment]
Thanks for your reporting. Would you like to share a link of the documentation that uses the _sessionEnabled_ property?

**Comment by leassis** [comment]
Sorry for late reply, this is the page that I've mentioned

https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-stream-binder/spring-cloud-azure-servicebus-topic-stream-binder

**Comment by yiliuTo** [comment]
Thank you, we will deal with this issue~

**Comment by saragluna** [comment]
Closing this issue.
