### ISSUE TITLE
service-bus: manual/Default checkpoint with sessions topics throws UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver. 

### ISSUE THREAD

**Issue by hemalathamoorthy** [microsoft/spring-cloud-azure#699]
This issue is same as https://github.com/microsoft/spring-cloud-azure/issues/594, only thing happens with the topics. Can you please resolve this.

**Comment by chenrujun** [comment]
@hemalathamoorthy 
Thanks for reporting it.

Could you please describe how to reproduce the problem? 

It's better to use our samples to reproduce your problem:
https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples

**Comment by chenrujun** [comment]
Hi, @hemalathamoorthy ,
I'll close this issue because there is no update for a long time.
