### ISSUE TITLE
Spring Boot app with Event Hub - doesn't work behind corporate firewall / doesn't pick proxy settings

### ISSUE THREAD

**Issue by yiliuTo** [microsoft/spring-cloud-azure#702]
This issue is similar to #656 however it appears with Event Hub now.

## Current Behavior
The proxy information can be set via the configuration after being updated to `com.azure:azure-messaging-eventhubs:5.1.0`, but **transportType** cannot be set as **AmqpWebSockets**. This causes an exception. It appears that `DefaultEventHubClientFactory` creates new `EventHubClientBuilders` and doesn't have a mechanism to set the **transporType.** 

If someone could add **transportType** to `AzureEventHubProperties` and pass it along to `clientBuilders` through the `clientFactory` that might solve the issue.

I was having trouble overwriting the `clientFactory` bean in our application to do this very thing. It seems that `AzureEventHubAutoConfiguration` is forcibly imported in `EventHubBinderConfiguration` which prevents our bean from being used. For some reason when we duplicate `EventHubBinderConfiguration` in our app to resolve the bean issue we loose the ability to publish/read from multiple eventhub namespaces.

## Possible Solution
Add **transportType** to `AzureEventHubProperties` and pass it along to `clientBuilders` through the `clientFactory`.

**Comment by MrOstling** [comment]
It would appear that in addition to the transportType addition, the  BlobContainerClientBuilder() needs to be passed an httpClient with proxies set.

**Comment by jpunlay** [comment]
Same here, ended up a having to implement our own `EventProcessorClient` because  of this. I think you're right, allowing for `transportType` in the properties could fix this.

**Comment by yiliuTo** [comment]
We currently do not support to set the `transportType` and will evaluate this as a feature.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
