### ISSUE TITLE
Unable to use credentials file on our host provider

### ISSUE THREAD

**Issue by MrOstling** [microsoft/spring-cloud-azure#703]
We are trying to use Eventhub in our cloud application but we don't have a secure way to include the necessary credentials file in the file system. The connection string and storage key used to be all we needed, but now it seems we are required to use MSI or a credentials file on the file system. We would like to use properties so that we can securely store our client secret in keyvault.     

## Expected Behavior
* I should be able to securely provide needed credentials from keyvault or properties from another source.

## Current Behavior
* Must store credentials in a file. 

## Possible Solution
* Add client id, secret, and tenant to the Azure properties and read them in the defaultCredentialsProvider. Something like
```
private String clientId;
private String clientSecret;
private String tenantId;
...
public boolean isCredentialed() {
        return StringUtils.hasText(getClientId())
                && StringUtils.hasText(getClientSecret())
                && StringUtils.hasText(getTenantId());
    }
```
and
```
private AzureTokenCredentials initCredentials(AzureProperties azureProperties) {
        if (azureProperties.isCredentialed()) {
            return new ApplicationTokenCredentials(azureProperties.getClientId(),
                    azureProperties.getTenantId(),
                    azureProperties.getClientSecret(),
                    AzureEnvironment.AZURE);
        }

        if (azureProperties.isMsiEnabled()) {
            AzureTokenCredentials credentials = getMSIToken(azureProperties);
            credentials.withDefaultSubscriptionId(azureProperties.getSubscriptionId());
            return credentials;
        }

        try {
            DefaultResourceLoader resourceLoader = new DefaultResourceLoader();
            InputStream inputStream =
                    resourceLoader.getResource(azureProperties.getCredentialFilePath()).getInputStream();
            File credentialFile = this.createTempCredentialFile(inputStream);

            return ApplicationTokenCredentials.fromFile(credentialFile);
        } catch (IOException e) {
            log.error("Credential file path not found.", e);
            throw new IllegalArgumentException("Credential file path not found", e);
        }
    }
```

## Your Environment
* Version used: 1.2.5

**Comment by yiliuTo** [comment]
Hi you can refer to [this sample](https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/eventhubs-binder-sample#credential-file-based-usage) for MSI or credential files based usage of event hub.

**Comment by MrOstling** [comment]
Please correct me if I'm wrong, but can't you only use MSI if you are hosted in an azure VM. Our project has a requirement to be hosted on an on prem corporate data center running PCF.

**Comment by yiliuTo** [comment]
Hi, thanks for reaching out. We will look into the usage of event hub on PCF with credential files.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
