### ISSUE TITLE
Subscriber not listening all messages from EventHub

### ISSUE THREAD

**Issue by musa4u** [microsoft/spring-cloud-azure#711]
We are trying to use Eventhub in our application as notification channel. Presently we are facing issue with subscribing the message, the subscriber picks 1 message out of 4 message. 

## Expected Behavior
To be subscribe all the messages from event hub

## Current Behavior
Subscriber not receiving all messages which are send by Publisher

## Snapshot Code for Reproduce 
```java
@Component
@EnableBinding(Sink.class)
public class HUDInvoiceEventListener {

    @StreamListener(Sink.INPUT)
    public void handleMessage(String message) throws Exception {
        System.out.println(String.format("New message received: '%s'", message));
    }
}
```
Sample Screenshot: We sent 15 request with message 1 to 15, but our subscriber receives only 4 out of 15.
![image](https://user-images.githubusercontent.com/20662907/84127018-4fc14200-aa5c-11ea-96aa-d2b16c9e8eca.png)

## Your Environment
* Version used: spring-cloud-azure-eventhubs-stream-binder
* Operating System and version (desktop or mobile): windows & linux (both platforms have it)
* SDK version: spring-cloud-azure-eventhubs-stream-binder 1.2.1

**Comment by saragluna** [comment]
Thanks for reaching out, could you try to upgrade to our latest release 1.2.6 to see whether the same issue exists?

**Comment by rodrigolopes** [comment]
we also have similar issue. Not all events sent are received by the consumer. We're using version 1.2.6.
We don't see any error or exception in logs

**Comment by saragluna** [comment]
@rodrigolopes Do you have a sample project that I could reproduce the issue?

**Comment by rodrigolopes** [comment]
I cleaned up some unrelated code, but the consumer is basically the below

`@EnableBinding(Sink.class)
public class AuditConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(AuditConfig.class);

    private final ObjectMapper objectMapper = new ObjectMapper();

    @StreamListener(Sink.INPUT)
    public void handle(Message<String> message, @Header(name = "messageType", required = false) String messageType) throws JsonProcessingException {
        if (MessageType.HEARTBEAT.name().equals(messageType)) {
            handleHeartbeatEvent(message);
        } else { // in case not all clients are sending the messageType header, we assume it's audit
            handleAuditEvent(message);
        }
        Metrics.counter("events.processed", "messageType", messageType).increment();
    }

    private void handleHeartbeatEvent(Message<String> message) {
        String heartbeat = message.getPayload();
        LOGGER.info("received heartbeat {}, at {}", heartbeat, Instant.now());
        heartbeatService.storeHeartbeat(heartbeat);
    }

    private void handleAuditEvent(Message<String> message) throws JsonProcessingException {
        String auditJson = message.getPayload();
        LOGGER.debug("Received auditVo: {}", auditJson);
   ….
    }

    @ServiceActivator(inputChannel = "audit.$Default.errors")
    public void consumerError(ErrorMessage errorMessage) {

        Message<?> originalMessage = errorMessage.getOriginalMessage();
        Throwable throwable = errorMessage.getPayload();
        Object originalPayload = null;
        String contentType = "audit";
        if (originalMessage != null) {
            originalPayload = originalMessage.getPayload();
            MimeType mimeType = originalMessage.getHeaders().get("contentType", MimeType.class);
            if (mimeType != null) {
                contentType = mimeType.toString();
            }
        }

        LOGGER.error("Error processing message {}. Error: {}", originalPayload, throwable);
        auditService.handleError(contentType, originalPayload, throwable);
    }
…
}`


properties:
`spring.cloud.azure.eventhub.namespace=***
spring.cloud.azure.eventhub.connection-string=*****
spring.cloud.azure.eventhub.checkpoint-storage-account=****
spring.cloud.azure.eventhub.checkpoint-container=events
spring.cloud.azure.eventhub.checkpoint-access-key=****
spring.cloud.stream.bindings.input.destination=***
spring.cloud.stream.bindings.input.group=$Default
spring.cloud.stream.eventhub.bindings.input.consumer.start-position=EARLIEST`

**Comment by saragluna** [comment]
@rodrigolopes Thanks for the info and we'll look into it.

**Comment by jochenvw** [comment]
@yiliuTo - do you suggest this team also tries the fix you suggested for issue #709 ?

**Comment by saragluna** [comment]
@rodrigolopes Sorry for the late response. Which version of the event-hub stream binder are you using?

**Comment by yiliuTo** [comment]
Hi @jochenvw @rodrigolopes , it seem this issue is not the same as 709 which is about failing to reconect to eventhubs and blobs after losing connections. And that issue is due to that an error code of losing connection did not be processed and event hub consumer tried to drain queues while the link processor had already been terminated thus stopping disconnection state being propagated to user application.

**Comment by musa4u** [comment]
> @rodrigolopes Sorry for the late response. Which version of the event-hub stream binder are you using?

**Comment by musa4u** [comment]
> @rodrigolopes Sorry for the late response. Which version of the event-hub stream binder are you using?

Initially we used 1.2.1 and then we upgraded to 1.2.6.

**Comment by rodrigolopes** [comment]
> > @rodrigolopes Sorry for the late response. Which version of the event-hub stream binder are you using?

We use 1.2.6

**Comment by saragluna** [comment]
@rodrigolopes 

Could you try with setting this property: `spring.cloud.stream.eventhub.bindings.input.consumer.checkpoint-mode=RECORD`?

Do you have a logging output that could help up debug? Also, could you set `logging.level.com.microsoft.azure.spring.integration.eventhub=debug` to see if the checkpoint works correctly?

**Comment by rodrigolopes** [comment]
sorry for late response. We were handling the issue via a Microsoft ticket. 
recreating the eventhubs and using the dependencies as below seems to have resolved the problem for us:
`		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>spring-cloud-azure-eventhubs-stream-binder</artifactId>
		    <version>1.2.6</version>
 		    <exclusions>
 		        <exclusion> 
 		            <groupId>com.azure</groupId>
 		            <artifactId>azure-messaging-eventhubs</artifactId>
 		        </exclusion>
 		        <exclusion>
 		            <groupId>com.azure</groupId>
 		            <artifactId>azure-core</artifactId>
 		        </exclusion>
 		    </exclusions>
		</dependency>
 		<dependency>
 		    <groupId>com.azure</groupId>
 		    <artifactId>azure-messaging-eventhubs</artifactId>
 		    <version>5.1.1</version>
 		</dependency>
 		<dependency>
 		    <groupId>com.azure</groupId>
 		    <artifactId>azure-core</artifactId>
 		    <version>1.5.1</version>
 		</dependency>`

**Comment by lu-cheng** [comment]
Any update on this issue?
