### ISSUE TITLE
EventHubTrigger not working with Spring Cloud

### ISSUE THREAD

**Issue by vermaaditya** [microsoft/spring-cloud-azure#720]
We are working on integrating the Azure EventHubTrigger Function with Spring Cloud Functions. I followed the below link which explains how HttpTrigger Function delegates the request to Spring Cloud. https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure When I try the same with EventHubTrigger, I get “Exception: IllegalStateException: No function defined”. Below is the screenshot of the log.

![image](https://user-images.githubusercontent.com/20763984/86221961-374bcf80-bba3-11ea-858e-ccf912004254.png)

***************
![image](https://user-images.githubusercontent.com/20763984/86221974-3d41b080-bba3-11ea-963a-eb1111d1639e.png)

***************
![image](https://user-images.githubusercontent.com/20763984/86221987-43379180-bba3-11ea-83d8-26347e124b89.png)

Please provide inputs or suggest what is it that we are doing wrong.

**Comment by moarychan** [comment]
Hi @vermaaditya , this repo does not have the integration feature of Spring Cloud Function & Azure Function, you can ask this issue in the following repo:

- https://github.com/Azure-Samples/hello-spring-function-azure/issues
- https://github.com/Azure/azure-functions-java-library/issues

Support team will reply to you. You can close this question here, thanks☺.
