### ISSUE TITLE
How Service Bus Binder to Support Scheduled Enqueue Message?

### ISSUE THREAD

**Issue by Simon-zhenfeng** [microsoft/spring-cloud-azure#731]
I want to send the **ScheduledEnqueue** Message by Service Bus Binder, is there any way to support it?

**Comment by yiliuTo** [comment]
Thanks for the reporing, we will investigate it.

**Comment by yiliuTo** [comment]
Hi @Simon-zhenfeng , we have implemented the feature about sending scheduledEnqueueMessage in servicebus binder [here](https://github.com/microsoft/spring-cloud-azure/pull/737), you could use the SNAPSHOT version and, before sending a message, add a header with key as "x-delay" and value as an Integer representing the number of milliseconds the message should be delayed.

**Comment by saragluna** [comment]
Implemented in #737.

**Comment by Simon-zhenfeng** [comment]
Hi @yiliuTo Thanks a lot.
