### ISSUE TITLE
App Configuration - Feature Filter mismatch between DotNet & Spring

### ISSUE THREAD

**Issue by mrm9084** [microsoft/spring-cloud-azure#746]
## Expected Behavior
* The feature filter conditions should have the same condition name. i.e. start and end. 

## Current Behavior
* Currently uses time-window-filter-setting-start and time-window-filter-setting-end

## Possible Solution
* Update Constants file with the new names

Reported https://github.com/Azure/AppConfiguration/issues/358

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
