### ISSUE TITLE
Azure storage overwrite  option not available

### ISSUE THREAD

**Issue by revoorunischal** [microsoft/spring-cloud-azure#749]
## Expected Behavior
When data is copied to particular file on cloud. if the file already exists. I want to overwrite it.

## Current Behavior
I get the following error if the file already exists
`java.lang.IllegalArgumentException: Blob already exists. Specify overwrite to true to force update the blob.
	at com.azure.storage.blob.specialized.BlockBlobClient.getBlobOutputStream(BlockBlobClient.java:100) ~[azure-storage-blob-12.5.0.jar:na]
	at com.azure.storage.blob.specialized.BlockBlobClient.getBlobOutputStream(BlockBlobClient.java:86) ~[azure-storage-blob-12.5.0.jar:na]
	at com.microsoft.azure.spring.cloud.storage.BlobStorageResource.getOutputStream(BlobStorageResource.java:67) ~[spring-cloud-azure-storage-1.2.7.jar:1.2.7]
	at com.finacle.cloudStorageReadWrite.Controller.uploadData(Controller.java:52) ~[classes/:na]`

## Possible Solution
Give an option to set this flag from resources 

## Steps to Reproduce (for bugs)
* step-1 - create a file in azure-blob 
* step-2 - try to replace the same file.

## Snapshot Code for Reproduce 
```java
 @GetMapping("/upload")
    public String uploadData(@RequestParam String url,@RequestParam String data){
        WritableResource resource = (WritableResource) resourceLoader.getResource(url);
        try (OutputStream outputStream = resource.getOutputStream()) {
            outputStream.write(data.getBytes(Charset.forName("UTF-8")));
            return "Success";
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "Fail";
    }
```

## Branch
1.2.7

## Your Environment
* Version used: 1.2.7
* Operating System and version (desktop or mobile): Mac , 
* SDK version: 1.2.7
* spring boot :  2.2.9.RELEASE and 2.3.1.RELEASE

**Comment by zhoufenqin** [comment]
Hi @revoorunischal, thanks for your feedback, actually we haven't support to override the blob yet. Maybe we can realize the feature later, now I need to investigate for this feature, will update the issue once we have a conclusion

**Comment by zhoufenqin** [comment]
@revoorunischal try to use the 1.2.8-SNAPSHOT. follow this link:https://github.com/microsoft/spring-cloud-azure#snapshots

**Comment by revoorunischal** [comment]
@zhoufenqin thank you it works fine now. But can I know when will this version be released?

 Since this needs to be added to production environment. I dont want to add a SNAPSHOT variant which keeps on changing.

**Comment by zhoufenqin** [comment]
> @zhoufenqin thank you it works fine now. But can I know when will this version be released?
> 
> Since this needs to be added to production environment. I dont want to add a SNAPSHOT variant which keeps on changing.

@saragluna do you know about it?

**Comment by saragluna** [comment]
@revoorunischal next release will be in several weeks.

**Comment by zhoufenqin** [comment]
Hi @revoorunischal, we have release the library.
The Storage Spring Boot Starter version:
```
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spring-starter-azure-storage</artifactId>
      <version>1.2.8</version>
</dependency>
```

The Spring Boot Storage version:
```
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spring-cloud-azure-storage</artifactId>
      <version>1.2.8</version> 
</dependency>
```

You can choose what you need.


Closing the issue
