### ISSUE TITLE
Getting error message - sent failed in async mode due to errorCondition[amqp:connection:framing-error]

### ISSUE THREAD

**Issue by forTechGig** [microsoft/spring-cloud-azure#753]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
private BinderAwareChannelResolver resolver;

when resolver.resolveDestination(channelName.toLowerCase()).send("message") is called, expect to return true when it is successfully sent and should see the message posted into eventhub

## Current Behavior
When the send() methos called, it returns **true** but the message is not posted into eventhub and we see below error message in our log:

sent failed in async mode due to errorCondition[amqp:connection:framing-error]. description[connection aborted], errorContext[NAMESPACE: XXXXXXX]

## Question:
1. Is there a way to enable sync mode. 
           In the class "DefaultMessageHandler" we see a method called "setSync" but couldn't figure out how to set it to true.

**Comment by lu-cheng** [comment]
@forTechGig 
You can refer to this documentation: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-cloud-eventhubs-stream-binder

Event Hub Producer Properties
It supports the following configurations with the format of spring.cloud.stream.eventhub.bindings.<channelName>.producer.

sync

Whether the producer should act in a synchronous manner with respect to writing messages into a stream. If true, the producer will wait for a response from Event Hub after a send operation.

Default: false

**Comment by forTechGig** [comment]
Thanks 👍 

That works for a specific channel. That did set the sync flag to true.

Question:
Is there a default config that we can set so that it will be applied to all the channels like below:
spring.cloud.stream.eventhub.bindings.**default**.producer

Right now we are posting to N number of channels. So adding this config for each and every channel is kind of making the things complicated.

**Comment by lu-cheng** [comment]
@forTechGig 

> Question:
> Is there a default config that we can set so that it will be applied to all the channels like below:
> spring.cloud.stream.eventhub.bindings.**default**.producer

Currently does not support setting like this.

**Comment by saragluna** [comment]
Closing this now.
