### ISSUE TITLE
Incorrect time comparison when use checkpoint-mode: TIME 

### ISSUE THREAD

**Issue by wedmeed** [microsoft/spring-cloud-azure#755]
https://github.com/microsoft/spring-cloud-azure/blob/5d883db6ad2243f59f93bf57037979c2b0214831/spring-integration-azure/spring-integration-eventhubs/src/main/java/com/microsoft/azure/spring/integration/eventhub/checkpoint/TimeCheckpointManager.java#L40

the comparison should be < 0 or Duration should be counted vice versa
<img width="923" alt="Screen Shot 2020-08-19 at 6 51 15 PM" src="https://user-images.githubusercontent.com/38181955/90650545-11f74b80-e24d-11ea-9d4b-8108c762ac9a.png">

**Comment by moarychan** [comment]
Hi @wedmeed , thank you for using, you are right, PR is coming soon.
