### ISSUE TITLE
Issues while upgrading to com.azure:azure-messaging-eventhubs:5.2.0

### ISSUE THREAD

**Issue by ShubhaPradeep** [microsoft/spring-cloud-azure#757]
We are trying to upgrade to azure-messaging-eventhubs:5.2.0 (earlier version was 5.1.0)as we had several issues while publishing to eventhub. One of the issues was "org.springframework.messaging.MessageDeliveryException: errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE".
After reading several blogs, we decided to upgrade to the latest version. But we have encountered issues related to other dependencies after the upgrade.
I would like to know what are the other dependencies we need to upgrade along with this?  Below are the dependencies we upgraded. 
implementation 'com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.2.0'
    implementation 'com.azure:azure-messaging-eventhubs:5.2.0'
 compile group: 'io.projectreactor', name: 'reactor-core', version: '3.3.10.RELEASE'

Below is the error we are seeing while testing:
Caused by: java.lang.IllegalStateException: Failed to register bean with name 'bf77d7d7-bb4d-4af5-b62f-f827d0b97422.bf77d7d7-bb4d-4af5-b62f-f827d0b97422.errors.recoverer', since bean with the same name already exists. Possible reason: You may have multiple bindings with the same 'destination' and 'group' name (consumer side) and multiple bindings with the same 'destination' name (producer side). Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side).

Please help.

**Comment by zhoufenqin** [comment]
hi @ShubhaPradeep, the repo has been migrated to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring, could you please create the issue there? should fill more issue details in azure-sdk-for-java repo

**Comment by ShubhaPradeep** [comment]
ok, thanks.

**Comment by zhoufenqin** [comment]
closing the issue, see https://github.com/Azure/azure-sdk-for-java/issues/15621
