### ISSUE TITLE
App Insight  Profiler not working for spring boot app in azure app services

### ISSUE THREAD

**Issue by oceansv** [microsoft/spring-cloud-azure#758]
We have integrated app insight for spring boot app which is deployed in azure app services , performance page in app insight is showing profile option but once triggered it says to wait for 18 mins but wither dont complete saying some exception occurred or no results .  How to profile our app. Is there some other profiling mechanism ?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
