### ISSUE TITLE
Fix broken links within this projects Readme

### ISSUE THREAD

**Issue by ulrichwinter** [microsoft/spring-cloud-azure#760]
The links to the spring-cloud-azure stream binder projects within the Readme are broken.

This pull request contains the correct links:
https://github.com/microsoft/spring-cloud-azure/pull/759

As this Readme is directly related in this github project, and not in the mentioned new location at https://github.com/Azure/azure-sdk-for-java/ I also opened this new issue here.

**Comment by saragluna** [comment]
Thanks for bringing this up, PR's been merged. Closing this issue now.
