### ISSUE TITLE
spring-cloud-azure-eventhubs-stream-binder:1.2.8 leads to NoSuchMethodError if used together with spring-cloud-azure-appconfiguration-config-web

### ISSUE THREAD

**Issue by ulrichwinter** [microsoft/spring-cloud-azure#761]
We use the following three dependencies in our maven-managed spring-boot project:
- com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.2.8
- com.microsoft.azure:spring-cloud-azure-appconfiguration-config-web:1.2.7
- com.microsoft.azure:spring-cloud-azure-feature-management-web:1.2.7

After upgrading the first one to release `1.2.8`, we encounter the following error during runtime, when a message is going to be sent to the eventhub:
```
java.lang.NoSuchMethodError: 'void com.azure.core.util.logging.ClientLogger.warning(java.lang.String)'
    at com.azure.core.amqp.implementation.AmqpChannelProcessor.onSubscribe(AmqpChannelProcessor.java:69)

```
For the other two depenencies, there is no `1.2.8` release available, so we must keep them on `1.2.7`.

The error can be reproduced with the following complete example project:
https://github.com/ulrichwinter/azure-eventhub-demo

I were only able to avoid this error, by reverting to the `1.2.7` release.
I also tried to avoid this situation using the `azure-spring-boot-bom`: the mentioned dependencies above still required manually defined versions.

How can I use the released ` com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.2.8` together with the mentioned appconfiguration and/or featuremanagement libs?

1. Please provide a way to declare consistently compatible dependency versions for spring-cloud-azure modules.
or:
2. Please provide newer releases for the mentioned spring-cloud-azure dependencies, which are compatible with the newest `spring-cloud-azure-eventhubs-stream-binder` release.

I also asked this question on stackoverflow:
https://stackoverflow.com/questions/65426745/how-should-spring-cloud-azure-dependencies-be-managed-in-a-spring-boot-service

**Comment by saragluna** [comment]
Thanks for reaching out to us. Since we've deprecated this repo and support all of our issues in the azure-sdk-for-java repo now. So I copied this issue there and will close this one now.
