### ISSUE TITLE
Bug: please allow to set jackson mapper into massage converters

### ISSUE THREAD

**Issue by dan1els** [microsoft/spring-cloud-azure#762]
The following class `com.azure.spring.integration.core.converter.AbstractAzureMessageConverter` has static dependency of jackson mapper. It makes mapper unconfigurable. Please make it non-static and provide ability to inject it through constructor.

**Comment by yiliuTo** [comment]
Hi @dan1els , thanks for your reporting, we will look into it. 
And would you share more details how you plan to use our library? Like are you going to use our stream binder library? Also the MessageConverter class or Template class?
Besides, given that you want to configure the mapper, may I know which properties of messages are you going to customize?
Thanks

**Comment by dan1els** [comment]
@yiliuTo Hi,
so we use azure-spring-cloud-starter-servicebus library for exchanging messages across our services. Our payloads (java dtos) might contain f.e. java8 date classes like Instant, LocalDate, etc. and ObjectMapper should be properly configured with modules like java-time as well.
So, as I figured out the class above is responsible for converting them.

**Comment by yiliuTo** [comment]
OK @dan1els, we will investigate and tyring to make it as a configurable bean.

**Comment by chenrujun** [comment]
We released [2.2.0](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-cloud-autoconfigure_2.2.0/sdk/spring/azure-spring-boot-starter-servicebus-jms/CHANGELOG.md#320-2021-03-03)

Please use the latest version.
