### ISSUE TITLE
can we specify partition key when producing events to event hubs using azure-spring-cloud-stream-binder-eventhubs ?

### ISSUE THREAD

**Issue by rodrigolopes** [microsoft/spring-cloud-azure#764]
I'd like to be able to specify a partition key when producing events to event hubs using azure-spring-cloud-stream-binder-eventhubs.
Is the property `spring.cloud.stream.bindings.<channelName>.producer.partitionKeyExpression` supported ?

**Comment by saragluna** [comment]
Hi @rodrigolopes, since we've deprecated this repo, I'm going to copy this issue to the new repo and answer it there. 

Closing this one now in favor of  https://github.com/Azure/azure-sdk-for-java/issues/19683.
