### ISSUE TITLE
Go through whole reference doc and fix errors

### ISSUE THREAD

**Issue by chenrujun** [microsoft/spring-cloud-azure#783]
Reference doc output: https://microsoft.github.io/spring-cloud-azure
Reference source code: https://github.com/microsoft/spring-cloud-azure/tree/docs

**Comment by hui1110** [comment]
Related PR has been merged.
https://github.com/microsoft/spring-cloud-azure/pull/787

**Comment by hui1110** [comment]
Related PR has been merged.
https://github.com/microsoft/spring-cloud-azure/pull/787
