### ISSUE TITLE
Go through whole migration guide and fix errors

### ISSUE THREAD

**Issue by chenrujun** [microsoft/spring-cloud-azure#784]
https://microsoft.github.io/spring-cloud-azure/docs/current/reference/html/appendix.html#migration-guide-for-4-0

**Comment by hui1110** [comment]
Related PR has been merged.
https://github.com/microsoft/spring-cloud-azure/pull/787

**Comment by hui1110** [comment]
Related PR has been merged.
https://github.com/microsoft/spring-cloud-azure/pull/787
