### ISSUE TITLE
Prepare Release Notes / Change Log for Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by chenrujun** [microsoft/spring-cloud-azure#785]
1. Release Notes put here: https://github.com/Azure/azure-sdk-for-java/releases
2. Change Log put here: https://github.com/Azure/azure-sdk-for-java/blob/feature/azure-spring-cloud-4.0/sdk/spring/CHANGELOG.md

Discuss with @seanli1988 about blog.

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/26304.
