### ISSUE TITLE
[FEATURE REQ] Add description of importing Spring Cloud Azure modules in Gradle to reference documentation

### ISSUE THREAD

**Issue by hui1110** [microsoft/spring-cloud-azure#932]
### Context
The two build tools `Maven` and `Gradle` are widely used. The [Spring Boot reference document](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools) describes how to import dependencies in `Maven` and `Gradle`.

### Problem
In [Spring Cloud Azure reference document](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#enable-health-indicator), we only have the description of import Spring Cloud Azure modules  in `Maven`.

### Goal

A description of how to import Spring Cloud Azure modules in `Maven` and `Gradle` should be included in the reference documentation.

**Comment by Netyyyy** [comment]
Closed for new docs described [here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/developer-guide-overview#bill-of-materials-bom)
