### ISSUE TITLE
MS Docs: Update the version of azure-keyvault-secrets-spring-boot-starter in azure-docs

### ISSUE THREAD

**Issue by chenrujun** [microsoft/spring-cloud-azure#963]
## Context

This issue is moved from https://github.com/MicrosoftDocs/azure-docs/issues/93940

`spring-cloud-azure-starter-keyvault-secrets:4.2.0` has released, we should use `spring-cloud-azure-starter-keyvault-secrets:4.2.0` instead of `azure-keyvault-secrets-spring-boot-starter` now.

#### Document Details

* Content: [Tutorial: Managed identity to connect Key Vault](https://docs.microsoft.com/en-us/azure/spring-cloud/tutorial-managed-identities-key-vault?tabs=system-assigned-managed-identity)
* Content Source: [articles/spring-cloud/tutorial-managed-identities-key-vault.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/spring-cloud/tutorial-managed-identities-key-vault.md)

### Goal
1. Replace `azure-keyvault-secrets-spring-boot-starter` by `spring-cloud-azure-starter-keyvault-secrets:4.2.0`.
2. Property names should be updated. For example: Use `spring.cloud.azure.keyvault.secret.xxx` instead of `azure.keyvault.xxx`. Refs: [migration-guide](https://microsoft.github.io/spring-cloud-azure/4.2.0/reference/html/appendix.html#_from_azure_spring_boot_starter_keyvault_secrets_to_spring_cloud_azure_starter_keyvault_secrets).

---

**Comment by moarychan** [comment]
Closing this due to the PR https://github.com/MicrosoftDocs/azure-docs/pull/97378 merged.
