### ISSUE TITLE
[FEATURE REQ] Make sure all Spring Cloud Azure related docs are updated

### ISSUE THREAD

**Issue by chenrujun** [microsoft/spring-cloud-azure#984]
### Context

Some `Spring Cloud Azure` related MS doc are always forgot to update. For example, this one: https://github.com/Azure/azure-sdk-for-java/issues/29863

### Goal

Design a method to make sure all `Spring Cloud Azure` related docs are updated in time.

### Solution proposal

1. Create a table. List all `Spring Cloud Azure` related docs. Write down when these pages should be updated.
2. Add the table to related wiki page: 
2.1. TODO list for a new release version of `Spring Boot`.
2.2. TOCO list for a new release version of `Spring Cloud Azure`.
2.3. etc.

Here is an example table:

| Link to docs | Should update when `Spring Boot` released a new version | Should update when `Spring Cloud Azure` released a new version | ... |
|---|---|---|---|
| [doc page 1](.) |:white_check_mark: |:x: | etc. |
| [doc page 2](.) | :x:|:white_check_mark: | |
| [doc page 3](.) | :x:|:white_check_mark: | |
| etc. | | | |

**Comment by stliu** [comment]
keep it simple
maybe ask our docs team and see if they have any suggestion

**Comment by Netyyyy** [comment]
Closed because it is no longer applicable
