### ISSUE TITLE
[FEATURE REQ] Add examples for configuring common properties

### ISSUE THREAD

**Issue by moarychan** [microsoft/spring-cloud-azure#985]
### Context
The Spring Cloud Azure supports lots of common properties since the 4.0 release, but the developers may be still not know how to use them, and how to combine them, there's no samples in our reference doc, such as [How to configure the retry options for KeyVault Clients when using Spring Cloud Azure Starter Key Vault Secert](https://github.com/MicrosoftDocs/azure-dev-docs/issues/863).

### Goal
Improve the reference doc to give more sample code to demo more user scenarios, we should cover the common use cases for the HTTP-based client option, amqp-based client option, and includes the Cosmos client options, which should contain the below items:
- Samples the global property options(retry, client(logging), proxy, [credential](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3369), profile, resource).
- Samples for each service property option (retry, client(logging), proxy, [credential](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3369), profile, resource).
- Maybe more special scenarios for Key Vault Secerts.

**Comment by moarychan** [comment]
Add retry configuration samples in this PR https://github.com/microsoft/spring-cloud-azure/issues/985

**Comment by Netyyyy** [comment]
close for moved to the above repo
