### ISSUE TITLE
[FEATURE REQ] Go through all the Spring Cloud Azure docs to make sure libs use the Passwordless best practices

### ISSUE THREAD

**Issue by saragluna** [microsoft/spring-cloud-azure#994]
**Is your feature request related to a problem? Please describe.**
The initiative comes from this [Cosmos quickstart doc](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db). In that doc, `spring.cloud.azure.cosmos.key` is being used instead of using the best practice of passwordless connection.

**Describe the solution you'd like**
We should go through all the docs we own and ensure they are using the passwordless connection.
Azure Services:
- App Configuration
- Cosmos
- Event Hubs
- Key Vault
- Service Bus
- Storage
- MySQL
- PostgreSQL
- Kafka

Hosting Env:
- Azure Spring Apps
- Azure App Service x Spring

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/30701

**Comment by stliu** [comment]
#30701 is for samething I believe

**Comment by stliu** [comment]
closing this in favor of https://github.com/Azure/azure-sdk-for-java/issues/30701
